///////////////////////////////////////////////////////////
//  Ciê¿arówka.cs
//  Implementation of the Class Ciê¿arówka
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:29
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ciê¿arówka : Pojazd {

	private List<string> historia tankowania;
	private Kierowca m_Kierowca;

	public Ciê¿arówka(){

	}

	~Ciê¿arówka(){

	}

	public Kierowca Kierowca{
		get{
			return m_Kierowca;
		}
		set{
			m_Kierowca = value;
		}
	}

}//end Ciê¿arówka