///////////////////////////////////////////////////////////
//  Dyspozytor.cs
//  Implementation of the Class Dyspozytor
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:29
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Dyspozytor : Osoba {

	private List<Zlecenie> przyjête zlecenia;
	private Lista zleceñ m_Lista zleceñ;

	public Dyspozytor(){

	}

	~Dyspozytor(){

	}

	public Lista zleceñ Lista zleceñ{
		get{
			return m_Lista zleceñ;
		}
		set{
			m_Lista zleceñ = value;
		}
	}

}//end Dyspozytor