///////////////////////////////////////////////////////////
//  Jednostka miary towaru.cs
//  Implementation of the Enumeration Jednostka miary towaru
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:29
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Jednostka miary towaru : int {

	szt,
	kg,
	m,
	m3

}//end Jednostka miary towaru