///////////////////////////////////////////////////////////
//  Kierownik.cs
//  Implementation of the Class Kierownik
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:29
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Kierownik : Osoba {

	private Raport m_Raport;
	private Lista kierowców m_Lista kierowców;
	private Lista pojazdów m_Lista pojazdów;

	public Kierownik(){

	}

	~Kierownik(){

	}

	public Lista kierowców Lista kierowców{
		get{
			return m_Lista kierowców;
		}
		set{
			m_Lista kierowców = value;
		}
	}

	public Lista pojazdów Lista pojazdów{
		get{
			return m_Lista pojazdów;
		}
		set{
			m_Lista pojazdów = value;
		}
	}

	public Raport Raport{
		get{
			return m_Raport;
		}
		set{
			m_Raport = value;
		}
	}

}//end Kierownik