///////////////////////////////////////////////////////////
//  Kierowca.cs
//  Implementation of the Class Kierowca
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:29
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Kierowca : Osoba {

	private List<Zlecenie> historia zleceñ;
	private string numer kierowcy;
	private Naczepa m_Naczepa;
	private Powiadomienie e-mail m_Powiadomienie e-mail;

	public Kierowca(){

	}

	~Kierowca(){

	}

	public Naczepa Naczepa{
		get{
			return m_Naczepa;
		}
		set{
			m_Naczepa = value;
		}
	}

	public Kierowca pobierz(){

		return null;
	}

	/// 
	/// <param name="pojazdy"></param>
	public void pobierzPrzypisanePojazdy(List<Pojazd> pojazdy){

	}

	public Powiadomienie e-mail Powiadomienie e-mail{
		get{
			return m_Powiadomienie e-mail;
		}
		set{
			m_Powiadomienie e-mail = value;
		}
	}

	public void usuñ(){

	}

	public Kierowca utwórz(){

		return null;
	}

	/// 
	/// <param name="kierowca"></param>
	public void zapisz(Kierowca kierowca){

	}

}//end Kierowca