///////////////////////////////////////////////////////////
//  Lista kierowców.cs
//  Implementation of the Class Lista kierowców
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Lista kierowców {

	private Kierowca m_Kierowca;
	private Ster_PrzypiszKierowcêDoZlecenia m_Ster_PrzypiszKierowcêDoZlecenia;

	public Lista kierowców(){

	}

	~Lista kierowców(){

	}

	/// 
	/// <param name="kierowca"></param>
	public void dodaj(Kierowca kierowca){

	}

	public Kierowca Kierowca{
		get{
			return m_Kierowca;
		}
		set{
			m_Kierowca = value;
		}
	}

	public Lista kierowców pobierz(){

		return null;
	}

	public Ster_PrzypiszKierowcêDoZlecenia Ster_PrzypiszKierowcêDoZlecenia{
		get{
			return m_Ster_PrzypiszKierowcêDoZlecenia;
		}
		set{
			m_Ster_PrzypiszKierowcêDoZlecenia = value;
		}
	}

	/// 
	/// <param name="kierowca"></param>
	public void usuñ(Kierowca kierowca){

	}

}//end Lista kierowców