///////////////////////////////////////////////////////////
//  Lista raportów.cs
//  Implementation of the Class Lista raportów
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Lista raportów {

	private Raport m_Raport;

	public Lista raportów(){

	}

	~Lista raportów(){

	}

	/// 
	/// <param name="raport"></param>
	public void dodaj(Raport raport){

	}

	public Lista raportów pobierz(){

		return null;
	}

	public Raport Raport{
		get{
			return m_Raport;
		}
		set{
			m_Raport = value;
		}
	}

}//end Lista raportów