///////////////////////////////////////////////////////////
//  Lista zleceñ.cs
//  Implementation of the Class Lista zleceñ
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Lista zleceñ {

	private Zlecenie m_Zlecenie;

	public Lista zleceñ(){

	}

	~Lista zleceñ(){

	}

	/// 
	/// <param name="zlecenie"></param>
	public void dodajZlecenie(Zlecenie zlecenie){

	}

	public List<Zlecenie> pobierzWszystkieZlecenia(){

		return null;
	}

	/// 
	/// <param name="zlecenie"></param>
	public List<Zlecenie> pobierzZleceniaKtóreMo¿naPo³¹czyæ(Zlecenie zlecenie){

		return null;
	}

	public Zlecenie Zlecenie{
		get{
			return m_Zlecenie;
		}
		set{
			m_Zlecenie = value;
		}
	}

}//end Lista zleceñ