///////////////////////////////////////////////////////////
//  Lista pojazdów.cs
//  Implementation of the Class Lista pojazdów
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Lista pojazdów {

	private Pojazd m_Pojazd;

	public Lista pojazdów(){

	}

	~Lista pojazdów(){

	}

	/// 
	/// <param name="pojazd"></param>
	public void dodaj(Pojazd pojazd){

	}

	public Lista pojazdów pobierz(){

		return null;
	}

	public Pojazd Pojazd{
		get{
			return m_Pojazd;
		}
		set{
			m_Pojazd = value;
		}
	}

	/// 
	/// <param name="pojazd"></param>
	public void usuñ(Pojazd pojazd){

	}

}//end Lista pojazdów