///////////////////////////////////////////////////////////
//  Naczepa.cs
//  Implementation of the Class Naczepa
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Naczepa : Pojazd {

	public Naczepa(){

	}

	~Naczepa(){

	}

}//end Naczepa