///////////////////////////////////////////////////////////
//  Osoba.cs
//  Implementation of the Class Osoba
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Osoba {

	private string email;
	private string imiê;
	private string nazwisko;
	private string pesel;
	private string telefon;
	private List<Uprawnienie> uprawnienia;

	public Osoba(){

	}

	~Osoba(){

	}

}//end Osoba