///////////////////////////////////////////////////////////
//  Pojazd.cs
//  Implementation of the Class Pojazd
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Pojazd {

	private string marka;
	private string model;
	private string numer rejestracyjny;
	private int przebieg;
	private Status pojazdu status;

	public Pojazd(){

	}

	~Pojazd(){

	}

	public Pojazd pobierz(){

		return null;
	}

	/// 
	/// <param name="kierowca"></param>
	public void przypiszKierowcê(Kierowca kierowca){

	}

	public void usuñ(){

	}

	public void usuñPrzypisanieKierowcy(){

	}

	public Pojazd utwórz(){

		return null;
	}

	/// 
	/// <param name="pojazd"></param>
	public void zapisz(Pojazd pojazd){

	}

}//end Pojazd