///////////////////////////////////////////////////////////
//  Powiadomienie e-mail.cs
//  Implementation of the Class Powiadomienie e-mail
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Powiadomienie e-mail {

	private Datetime czas akceptacji zlecenia;
	private Status powiadomienia o zleceniu status;

	public Powiadomienie e-mail(){

	}

	~Powiadomienie e-mail(){

	}

	public Powiadomienie e-mail utwórz(){

		return null;
	}

}//end Powiadomienie e-mail