///////////////////////////////////////////////////////////
//  Po³o¿enie ciê¿arówki.cs
//  Implementation of the Class Po³o¿enie ciê¿arówki
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Po³o¿enie ciê¿arówki {

	private Datetime czas;
	private string wspó³rzêdne;

	public Po³o¿enie ciê¿arówki(){

	}

	~Po³o¿enie ciê¿arówki(){

	}

	public void utwórz(){

	}

}//end Po³o¿enie ciê¿arówki