///////////////////////////////////////////////////////////
//  Punkt docelowy.cs
//  Implementation of the Class Punkt docelowy
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Punkt docelowy {

	private string nazwa;
	private bool odwiedzony;
	private string wspó³rzêdne;

	public Punkt docelowy(){

	}

	~Punkt docelowy(){

	}

	public Punkt docelowy pobierz(){

		return null;
	}

}//end Punkt docelowy