///////////////////////////////////////////////////////////
//  Raport.cs
//  Implementation of the Class Raport
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Raport {

	private Kierownik autor;
	private Datetime czas wygenerowania;
	private Rodzaj raportu rodzaj;
	private Szablon raportu m_Szablon raportu;

	public Raport(){

	}

	~Raport(){

	}

	public Szablon raportu Szablon raportu{
		get{
			return m_Szablon raportu;
		}
		set{
			m_Szablon raportu = value;
		}
	}

}//end Raport