///////////////////////////////////////////////////////////
//  Rodzaj zdarzenia na trasie.cs
//  Implementation of the Enumeration Rodzaj zdarzenia na trasie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Rodzaj zdarzenia na trasie : int {

	podró¿ promem,
	tankowanie,
	awaria,
	problem,
	wyjazd w trasê,
	zakoñczenie trasy,
	roz³adunek,
	inne

}//end Rodzaj zdarzenia na trasie