///////////////////////////////////////////////////////////
//  Rodzaj raportu.cs
//  Implementation of the Enumeration Rodzaj raportu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Rodzaj raportu : int {

	okresowy z wielu zleceñ,
	okresowy dla kierowcy,
	okresowy dla ciê¿arówki,
	okresowy dla spedycji,
	ze zlecenia

}//end Rodzaj raportu