///////////////////////////////////////////////////////////
//  Status zlecenia.cs
//  Implementation of the Enumeration Status zlecenia
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Status zlecenia : int {

	Dodane,
	Przyjête do realizacji,
	Zaplanowana trasa,
	W trakcie realizacji,
	Zrealizowane,
	Anulowane

}//end Status zlecenia