///////////////////////////////////////////////////////////
//  Status powiadomienia o zleceniu.cs
//  Implementation of the Enumeration Status powiadomienia o zleceniu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Status powiadomienia o zleceniu : int {

	wys³ane do kierowcy,
	zlecenie zaakceptowane,
	nieaktualne

}//end Status powiadomienia o zleceniu