///////////////////////////////////////////////////////////
//  Status pojazdu.cs
//  Implementation of the Enumeration Status pojazdu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Status pojazdu : int {

	w trasie,
	dostêpny,
	awaria,
	w naprawie,
	serwis

}//end Status pojazdu