///////////////////////////////////////////////////////////
//  Szablon raportu.cs
//  Implementation of the Class Szablon raportu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:31
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Szablon raportu {

	private HTML struktura;
	private CSS styl;

	public Szablon raportu(){

	}

	~Szablon raportu(){

	}

}//end Szablon raportu