///////////////////////////////////////////////////////////
//  Towar.cs
//  Implementation of the Class Towar
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:31
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Towar {

	private double iloœæ;
	private Jednostka miary towaru jednostka;
	private string nazwa;
	private Zlecenie m_Zlecenie;

	public Towar(){

	}

	~Towar(){

	}

	public Zlecenie Zlecenie{
		get{
			return m_Zlecenie;
		}
		set{
			m_Zlecenie = value;
		}
	}

}//end Towar