///////////////////////////////////////////////////////////
//  Trasa.cs
//  Implementation of the Class Trasa
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:31
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Trasa {

	private Datetime czas wyjazdu;
	private Datetime czas zakoñczenia;
	private int d³ugoœæ;
	private Punkt docelowy m_Punkt docelowy;
	private Zlecenie m_Zlecenie;
	private Zdarzenie na trasie m_Zdarzenie na trasie;

	public Trasa(){

	}

	~Trasa(){

	}

	/// 
	/// <param name="punkty docelowe"></param>
	public void aktualizuj(List<Punkt docelowy> punkty docelowe){

	}

	/// 
	/// <param name="zdarzenie"></param>
	public void dodajZdarzenie(Zdarzenie na trasie zdarzenie){

	}

	public Trasa pobierz(){

		return null;
	}

	public Punkt docelowy Punkt docelowy{
		get{
			return m_Punkt docelowy;
		}
		set{
			m_Punkt docelowy = value;
		}
	}

	/// 
	/// <param name="zlecenia"></param>
	public void ustawPasuj¹ceZlecenia(List<Zlecenie> zlecenia){

	}

	/// 
	/// <param name="punkty docelowe"></param>
	public Trasa utwórz(List<Punkt docelowy> punkty docelowe){

		return null;
	}

	public void zarejestrujKoniecZlecenia(){

	}

	public void zarejestrujWyjazd(){

	}

	public Zdarzenie na trasie Zdarzenie na trasie{
		get{
			return m_Zdarzenie na trasie;
		}
		set{
			m_Zdarzenie na trasie = value;
		}
	}

	public Zlecenie Zlecenie{
		get{
			return m_Zlecenie;
		}
		set{
			m_Zlecenie = value;
		}
	}

}//end Trasa