///////////////////////////////////////////////////////////
//  Uprawnienie.cs
//  Implementation of the Enumeration Uprawnienie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:31
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Uprawnienie : int {

	generowanie raportów,
	przyjmowanie zleceñ do realizacji,
	realizacja trasy,
	planowanie trasy,
	zarz¹dzanie kierowcami,
	zarz¹dzanie zleceniami,
	dodawanie zleceñ,
	zarz¹dzanie pojazdami

}//end Uprawnienie