///////////////////////////////////////////////////////////
//  Zdarzenie na trasie.cs
//  Implementation of the Class Zdarzenie na trasie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:31
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Zdarzenie na trasie {

	private string opis;
	private Rodzaj zdarzenia na trasie rodzaj;
	private Po³o¿enie ciê¿arówki m_Po³o¿enie ciê¿arówki;
	private Ster_ZarejestrujZdarzenieNaTrasie m_Ster_ZarejestrujZdarzenieNaTrasie;

	public Zdarzenie na trasie(){

	}

	~Zdarzenie na trasie(){

	}

	public Po³o¿enie ciê¿arówki Po³o¿enie ciê¿arówki{
		get{
			return m_Po³o¿enie ciê¿arówki;
		}
		set{
			m_Po³o¿enie ciê¿arówki = value;
		}
	}

	public Ster_ZarejestrujZdarzenieNaTrasie Ster_ZarejestrujZdarzenieNaTrasie{
		get{
			return m_Ster_ZarejestrujZdarzenieNaTrasie;
		}
		set{
			m_Ster_ZarejestrujZdarzenieNaTrasie = value;
		}
	}

	public Zdarzenie na trasie utwórz(){

		return null;
	}

}//end Zdarzenie na trasie