///////////////////////////////////////////////////////////
//  Zlecenie.cs
//  Implementation of the Class Zlecenie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 21:24:31
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Zlecenie {

	private Datetime czas dodania;
	private Datetime czas przyjêcia do realizacji;
	private Datetime czas ukoñczenia;
	private int id;
	private string nazwa klienta;
	private Status zlecenia status;
	private Powiadomienie e-mail m_Powiadomienie e-mail;
	private Ster_PrzypiszKierowcêDoZlecenia m_Ster_PrzypiszKierowcêDoZlecenia;

	public Zlecenie(){

	}

	~Zlecenie(){

	}

	public Zlecenie pobierz(){

		return null;
	}

	public Powiadomienie e-mail Powiadomienie e-mail{
		get{
			return m_Powiadomienie e-mail;
		}
		set{
			m_Powiadomienie e-mail = value;
		}
	}

	/// 
	/// <param name="kierowca"></param>
	public void przypiszKierowcê(Kierowca kierowca){

	}

	public Ster_PrzypiszKierowcêDoZlecenia Ster_PrzypiszKierowcêDoZlecenia{
		get{
			return m_Ster_PrzypiszKierowcêDoZlecenia;
		}
		set{
			m_Ster_PrzypiszKierowcêDoZlecenia = value;
		}
	}

	public void zapisz(){

	}

	/// 
	/// <param name="kierowca"></param>
	public void zarejestrujPrzyjêcieZlecenia(Kierowca kierowca){

	}

}//end Zlecenie