///////////////////////////////////////////////////////////
//  FormularzKierownika_ZmodyfikujPrzypisaniePojazdówDoKierowcy.cs
//  Implementation of the Class FormularzKierownika_ZmodyfikujPrzypisaniePojazdówDoKierowcy
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:05:51
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_ZmodyfikujPrzypisaniePojazdówDoKierowcy {

	private Kierowca kierowca;
	private List<Pojazd> pojazdy;

	public FormularzKierownika_ZmodyfikujPrzypisaniePojazdówDoKierowcy(){

	}

	~FormularzKierownika_ZmodyfikujPrzypisaniePojazdówDoKierowcy(){

	}

	/// 
	/// <param name="kryteria"></param>
	public void filtrujListêPojazdów(List<string> kryteria){

	}

	/// 
	/// <param name="pojazd"></param>
	/// <param name="kierowca"></param>
	public void przypiszPojazdDoKierowcy(Pojazd pojazd, Kierowca kierowca){

	}

	public Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy{
		get{
			return m_Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy;
		}
		set{
			m_Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy = value;
		}
	}

	/// 
	/// <param name="pojazd"></param>
	public void usuñPrzypisaniePojazduDoKierowcy(Pojazd pojazd){

	}

	/// 
	/// <param name="kierowca"></param>
	public void wyœwietlFormularzPrzypisaniaPojazdówDoKierowcy(Kierowca kierowca){

	}

	/// 
	/// <param name="pojazdy"></param>
	public void wyœwietlListêPojazdów(Lista pojazdów pojazdy){

	}

	/// 
	/// <param name="pojazd"></param>
	public void wyœwietlMenuKontekstowe(Pojazd pojazd){

	}

	/// 
	/// <param name="pojazd"></param>
	public void zaznaczPojazd(Pojazd pojazd){

	}

}//end FormularzKierownika_ZmodyfikujPrzypisaniePojazdówDoKierowcy