///////////////////////////////////////////////////////////
//  FormularzKierownika_EdytujDaneKierowcy.cs
//  Implementation of the Class FormularzKierownika_EdytujDaneKierowcy
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:05:40
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_EdytujDaneKierowcy {

	private Kierowca kierowca;

	public FormularzKierownika_EdytujDaneKierowcy(){

	}

	~FormularzKierownika_EdytujDaneKierowcy(){

	}

	public Ster_EdytujDaneKierowcy Ster_EdytujDaneKierowcy{
		get{
			return m_Ster_EdytujDaneKierowcy;
		}
		set{
			m_Ster_EdytujDaneKierowcy = value;
		}
	}

	/// 
	/// <param name="b³êdy"></param>
	public void wyœwietlB³êdy(List<string> b³êdy){

	}

	public void wyœwietlFormularzEdycjiDanychKierowcy(){

	}

	public void zapisz(){

	}

}//end FormularzKierownika_EdytujDaneKierowcy