///////////////////////////////////////////////////////////
//  FormularzKierownika_DodajNowegoKierowcê.cs
//  Implementation of the Class FormularzKierownika_DodajNowegoKierowcê
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:05:36
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_DodajNowegoKierowcê {

	private Kierowca kierowca;

	public FormularzKierownika_DodajNowegoKierowcê(){

	}

	~FormularzKierownika_DodajNowegoKierowcê(){

	}

	public void dodajKierowcê(){

	}

	public Ster_DodajNowegoKierowcê Ster_DodajNowegoKierowcê{
		get{
			return m_Ster_DodajNowegoKierowcê;
		}
		set{
			m_Ster_DodajNowegoKierowcê = value;
		}
	}

}//end FormularzKierownika_DodajNowegoKierowcê