///////////////////////////////////////////////////////////
//  FormularzKierownika_UsuñIstniej¹cegoKierowcê.cs
//  Implementation of the Class FormularzKierownika_UsuñIstniej¹cegoKierowcê
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:05:43
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_UsuñIstniej¹cegoKierowcê {

	private Kierowca kierowca;

	public FormularzKierownika_UsuñIstniej¹cegoKierowcê(){

	}

	~FormularzKierownika_UsuñIstniej¹cegoKierowcê(){

	}

	public Ster_UsuñIstniej¹cegoKierowcê Ster_UsuñIstniej¹cegoKierowcê{
		get{
			return m_Ster_UsuñIstniej¹cegoKierowcê;
		}
		set{
			m_Ster_UsuñIstniej¹cegoKierowcê = value;
		}
	}

	/// 
	/// <param name="kierowca"></param>
	public void usuñKierowcê(Kierowca kierowca){

	}

	/// 
	/// <param name="kierowca"></param>
	public void wyœwietlMenuKontekstowe(Kierowca kierowca){

	}

	/// 
	/// <param name="kierowca"></param>
	public void zaznaczKierowcê(Kierowca kierowca){

	}

}//end FormularzKierownika_UsuñIstniej¹cegoKierowcê