///////////////////////////////////////////////////////////
//  FormularzKierownika_ZaktualizujDaneIstniej¹cegoKierowcy.cs
//  Implementation of the Class FormularzKierownika_ZaktualizujDaneIstniej¹cegoKierowcy
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:05:47
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_ZaktualizujDaneIstniej¹cegoKierowcy {

	private Kierowca kierowca;

	public FormularzKierownika_ZaktualizujDaneIstniej¹cegoKierowcy(){

	}

	~FormularzKierownika_ZaktualizujDaneIstniej¹cegoKierowcy(){

	}

	/// 
	/// <param name="kierowca"></param>
	public void edytuj(Kierowca kierowca){

	}

	public Ster_ZaktualizujDaneIstniej¹cegoKierowcy Ster_ZaktualizujDaneIstniej¹cegoKierowcy{
		get{
			return m_Ster_ZaktualizujDaneIstniej¹cegoKierowcy;
		}
		set{
			m_Ster_ZaktualizujDaneIstniej¹cegoKierowcy = value;
		}
	}

	public void wyœwietlFormularzAktualizacjiDanychKierowcy(){

	}

	/// 
	/// <param name="kierowcy"></param>
	public void wyœwietlListêKierowców(Lista kierowców kierowcy){

	}

	/// 
	/// <param name="kierowca"></param>
	public void wyœwietlMenuKontekstowe(Kierowca kierowca){

	}

	/// 
	/// <param name="kierowca"></param>
	public void zaznaczKierowcê(Kierowca kierowca){

	}

}//end FormularzKierownika_ZaktualizujDaneIstniej¹cegoKierowcy