///////////////////////////////////////////////////////////
//  Ster_EdytujDaneKierowcy.cs
//  Implementation of the Class Ster_EdytujDaneKierowcy
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:14:44
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_EdytujDaneKierowcy {

	private Kierowca kierowca;

	public Ster_EdytujDaneKierowcy(){

	}

	~Ster_EdytujDaneKierowcy(){

	}

	public Kierowca Kierowca{
		get{
			return kierowca;
		}
		set{
			kierowca = value;
		}
	}

	public void pobierzDostêpnePojazdy(){

	}

	/// 
	/// <param name="kierowca"></param>
	public void waliduj(Kierowca kierowca){

	}

	/// 
	/// <param name="kierowca"></param>
	public void zapisz(Kierowca kierowca){

	}

}//end Ster_EdytujDaneKierowcy