///////////////////////////////////////////////////////////
//  Ster_UsuñIstniej¹cegoKierowcê.cs
//  Implementation of the Class Ster_UsuñIstniej¹cegoKierowcê
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:14:48
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_UsuñIstniej¹cegoKierowcê {

	private Kierowca kierowca;

	public Ster_UsuñIstniej¹cegoKierowcê(){

	}

	~Ster_UsuñIstniej¹cegoKierowcê(){

	}

	public Kierowca Kierowca{
		get{
			return kierowca;
		}
		set{
			kierowca = value;
		}
	}

	public Lista kierowców Lista kierowców{
		get{
			return m_Lista kierowców;
		}
		set{
			m_Lista kierowców = value;
		}
	}

	public Pojazd Pojazd{
		get{
			return m_Pojazd;
		}
		set{
			m_Pojazd = value;
		}
	}

	/// 
	/// <param name="kierowca"></param>
	public void usuñKierowcê(Kierowca kierowca){

	}

}//end Ster_UsuñIstniej¹cegoKierowcê