///////////////////////////////////////////////////////////
//  Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy.cs
//  Implementation of the Class Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:14:55
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy {

	private Kierowca kierowca;
	private List<Pojazd> pojazdy;

	public Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy(){

	}

	~Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy(){

	}

	public Lista pojazdów Lista pojazdów{
		get{
			return m_Lista pojazdów;
		}
		set{
			m_Lista pojazdów = value;
		}
	}

	public Lista pojazdów pobierzListêPojazdów(){

		return null;
	}

	public Pojazd Pojazd{
		get{
			return m_Pojazd;
		}
		set{
			m_Pojazd = value;
		}
	}

	/// 
	/// <param name="pojazd"></param>
	/// <param name="kierowca"></param>
	public void przypiszPojazdDoKierowcy(Pojazd pojazd, Kierowca kierowca){

	}

	/// 
	/// <param name="pojazd"></param>
	public void usuñPrzypisaniePojazduDoKierowcy(Pojazd pojazd){

	}

}//end Ster_ZmodyfikujPrzypisaniePojazdówDoKierowcy