///////////////////////////////////////////////////////////
//  Ster_ZaktualizujDaneIstniej¹cegoKierowcy.cs
//  Implementation of the Class Ster_ZaktualizujDaneIstniej¹cegoKierowcy
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:14:51
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZaktualizujDaneIstniej¹cegoKierowcy {

	private Kierowca kierowca;

	public Ster_ZaktualizujDaneIstniej¹cegoKierowcy(){

	}

	~Ster_ZaktualizujDaneIstniej¹cegoKierowcy(){

	}

	public Lista kierowców Lista kierowców{
		get{
			return m_Lista kierowców;
		}
		set{
			m_Lista kierowców = value;
		}
	}

	public Lista kierowców pobierzListêKierowców(){

		return null;
	}

}//end Ster_ZaktualizujDaneIstniej¹cegoKierowcy