///////////////////////////////////////////////////////////
//  Ster_DodajNowegoKierowcê.cs
//  Implementation of the Class Ster_DodajNowegoKierowcê
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:14:41
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_DodajNowegoKierowcê {

	private Kierowca kierowca;

	public Ster_DodajNowegoKierowcê(){

	}

	~Ster_DodajNowegoKierowcê(){

	}

	public Kierowca Kierowca{
		get{
			return kierowca;
		}
		set{
			kierowca = value;
		}
	}

	public Lista kierowców Lista kierowców{
		get{
			return m_Lista kierowców;
		}
		set{
			m_Lista kierowców = value;
		}
	}

	public Kierowca utwórzKierowcê(){

		return null;
	}

}//end Ster_DodajNowegoKierowcê