///////////////////////////////////////////////////////////
//  FormularzDyspozytora_PrzypiszKierowcêDoZlecenia.cs
//  Implementation of the Class FormularzDyspozytora_PrzypiszKierowcêDoZlecenia
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 19:59:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzDyspozytora_PrzypiszKierowcêDoZlecenia {

	private Kierowca Kierowca;
	private Zlecenie zlecenie;

	public FormularzDyspozytora_PrzypiszKierowcêDoZlecenia(){

	}

	~FormularzDyspozytora_PrzypiszKierowcêDoZlecenia(){

	}

	/// 
	/// <param name="kryteria"></param>
	public void filtrujListêKierowców(List<string> kryteria){

	}

	/// 
	/// <param name="kierowca"></param>
	/// <param name="zlecenie"></param>
	public void przypiszKierowcêDoZlecenia(Kierowca kierowca, Zlecenie zlecenie){

	}

	public void wyœwietlListêKierowców(){

	}

	/// 
	/// <param name="kierowca"></param>
	public void wyœwietlMenuKontekstowe(Kierowca kierowca){

	}

	/// 
	/// <param name="kierowca"></param>
	public void zaznaczKierowcê(Kierowca kierowca){

	}

}//end FormularzDyspozytora_PrzypiszKierowcêDoZlecenia