///////////////////////////////////////////////////////////
//  FormularzDyspozytora_WybierzZlecenieZListyDostêpnychZleceñ.cs
//  Implementation of the Class FormularzDyspozytora_WybierzZlecenieZListyDostêpnychZleceñ
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 19:59:45
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzDyspozytora_WybierzZlecenieZListyDostêpnychZleceñ {

	private Zlecenie zlecenie;

	public FormularzDyspozytora_WybierzZlecenieZListyDostêpnychZleceñ(){

	}

	~FormularzDyspozytora_WybierzZlecenieZListyDostêpnychZleceñ(){

	}

	/// 
	/// <param name="zlecenie"></param>
	public void przyjmijZlecenieDoRealizacji(Zlecenie zlecenie){

	}

	public Ster_WybierzZlecenieZListyDostêpnychZleceñ Ster_WybierzZlecenieZListyDostêpnychZleceñ{
		get{
			return m_Ster_WybierzZlecenieZListyDostêpnychZleceñ;
		}
		set{
			m_Ster_WybierzZlecenieZListyDostêpnychZleceñ = value;
		}
	}

	public void wyœwietlListêZleceñ(){

	}

}//end FormularzDyspozytora_WybierzZlecenieZListyDostêpnychZleceñ