///////////////////////////////////////////////////////////
//  FormularzDyspozytora_ZaplanujTrasê.cs
//  Implementation of the Class FormularzDyspozytora_ZaplanujTrasê
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 19:59:50
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzDyspozytora_ZaplanujTrasê {

	private List<Punkt docelowy> punkty docelowe;
	private Zlecenie zlecenie;

	public FormularzDyspozytora_ZaplanujTrasê(){

	}

	~FormularzDyspozytora_ZaplanujTrasê(){

	}

	/// 
	/// <param name="trasa"></param>
	public void edytujPunktyDocelowe(Trasa trasa){

	}

	/// 
	/// <param name="zlecenia"></param>
	public Trasa po³¹czZlecenia(List<Zlecenie> zlecenia){

		return null;
	}

	public Ster_ZaplanujTrasê Ster_ZaplanujTrasê{
		get{
			return m_Ster_ZaplanujTrasê;
		}
		set{
			m_Ster_ZaplanujTrasê = value;
		}
	}

	/// 
	/// <param name="zlecenie"></param>
	public void wyœwietlFormularzEdycjiTrasy(Zlecenie zlecenie){

	}

	public void wyœwietlKomunikatOZapisaniu(){

	}

	/// 
	/// <param name="trasa"></param>
	public void wyœwietlListêZleceñKtóreMo¿naPo³¹czyæ(Trasa trasa){

	}

	/// 
	/// <param name="trasa"></param>
	public void wyœwietlTrasêNaMapie(Trasa trasa){

	}

}//end FormularzDyspozytora_ZaplanujTrasê