///////////////////////////////////////////////////////////
//  FormularzSpedytora_DodajZlecenieDoSystemu.cs
//  Implementation of the Class FormularzSpedytora_DodajZlecenieDoSystemu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 19:59:53
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzSpedytora_DodajZlecenieDoSystemu {

	private Zlecenie zlecenie;

	public FormularzSpedytora_DodajZlecenieDoSystemu(){

	}

	~FormularzSpedytora_DodajZlecenieDoSystemu(){

	}

	public Ster_DodajZlecenieDoSystemu Ster_DodajZlecenieDoSystemu{
		get{
			return m_Ster_DodajZlecenieDoSystemu;
		}
		set{
			m_Ster_DodajZlecenieDoSystemu = value;
		}
	}

	/// 
	/// <param name="zlecenie"></param>
	public void wybierzZlecenieDoImportu(Zlecenie zlecenie){

	}

	public void wyœwietlListêZleceñDoImportu(){

	}

}//end FormularzSpedytora_DodajZlecenieDoSystemu