///////////////////////////////////////////////////////////
//  Ster_PrzypiszKierowcêDoZlecenia.cs
//  Implementation of the Class Ster_PrzypiszKierowcêDoZlecenia
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:12:04
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_PrzypiszKierowcêDoZlecenia {

	private Kierowca kierowca;
	private Zlecenie zlecenie;
	private FormularzDyspozytora_PrzypiszKierowcêDoZlecenia m_FormularzDyspozytora_PrzypiszKierowcêDoZlecenia;

	public Ster_PrzypiszKierowcêDoZlecenia(){

	}

	~Ster_PrzypiszKierowcêDoZlecenia(){

	}

	public FormularzDyspozytora_PrzypiszKierowcêDoZlecenia FormularzDyspozytora_PrzypiszKierowcêDoZlecenia{
		get{
			return m_FormularzDyspozytora_PrzypiszKierowcêDoZlecenia;
		}
		set{
			m_FormularzDyspozytora_PrzypiszKierowcêDoZlecenia = value;
		}
	}

	public Lista kierowców pobierzListêKierowców(){

		return null;
	}

	/// 
	/// <param name="kierowca"></param>
	/// <param name="zlecenie"></param>
	public void przypiszKierowcêDoZlecenia(Kierowca kierowca, Zlecenie zlecenie){

	}

	/// 
	/// <param name="powiadomienie"></param>
	/// <param name="kierowca"></param>
	public void wyœlijPowiadomienieDoKierowcy(Powiadomienie e-mail powiadomienie, Kierowca kierowca){

	}

}//end Ster_PrzypiszKierowcêDoZlecenia