///////////////////////////////////////////////////////////
//  Ster_DodajZlecenieDoSystemu.cs
//  Implementation of the Class Ster_DodajZlecenieDoSystemu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:11:59
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_DodajZlecenieDoSystemu {

	private Zlecenie zlecenie;

	public Ster_DodajZlecenieDoSystemu(){

	}

	~Ster_DodajZlecenieDoSystemu(){

	}

	public Lista zleceñ Lista zleceñ{
		get{
			return m_Lista zleceñ;
		}
		set{
			m_Lista zleceñ = value;
		}
	}

	public List<Zlecenie> pobierzListêZleceñDostêpnychDoZaimportowania(){

		return null;
	}

	/// 
	/// <param name="zlecenie"></param>
	public void zaimportujZlecenie(Zlecenie zlecenie){

	}

	public Zlecenie Zlecenie{
		get{
			return zlecenie;
		}
		set{
			zlecenie = value;
		}
	}

}//end Ster_DodajZlecenieDoSystemu