///////////////////////////////////////////////////////////
//  Ster_ZaplanujTrasê.cs
//  Implementation of the Class Ster_ZaplanujTrasê
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:12:11
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZaplanujTrasê {

	private List<Punkt docelowy> punkty docelowe;
	private Zlecenie zlecenie;

	public Ster_ZaplanujTrasê(){

	}

	~Ster_ZaplanujTrasê(){

	}

	public Lista zleceñ Lista zleceñ{
		get{
			return m_Lista zleceñ;
		}
		set{
			m_Lista zleceñ = value;
		}
	}

	/// 
	/// <param name="zlecenie"></param>
	public Trasa pobierzTrasê(Zlecenie zlecenie){

		return null;
	}

	/// 
	/// <param name="zlecenia"></param>
	public Trasa po³¹czZlecenia(List<Zlecenie> zlecenia){

		return null;
	}

	public Punkt docelowy Punkt docelowy{
		get{
			return m_Punkt docelowy;
		}
		set{
			m_Punkt docelowy = value;
		}
	}

	public Trasa Trasa{
		get{
			return m_Trasa;
		}
		set{
			m_Trasa = value;
		}
	}

	/// 
	/// <param name="trasa"></param>
	public void zapiszPunktyDocelowe(Trasa trasa){

	}

}//end Ster_ZaplanujTrasê