///////////////////////////////////////////////////////////
//  Ster_WybierzZlecenieZListyDostêpnychZleceñ.cs
//  Implementation of the Class Ster_WybierzZlecenieZListyDostêpnychZleceñ
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:12:07
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_WybierzZlecenieZListyDostêpnychZleceñ {

	private Zlecenie zlecenie;

	public Ster_WybierzZlecenieZListyDostêpnychZleceñ(){

	}

	~Ster_WybierzZlecenieZListyDostêpnychZleceñ(){

	}

	public Lista zleceñ Lista zleceñ{
		get{
			return m_Lista zleceñ;
		}
		set{
			m_Lista zleceñ = value;
		}
	}

	public List<Zlecenie> pobierzListêZleceñ(){

		return null;
	}

	/// 
	/// <param name="zlecenie"></param>
	public void przyjmijZlecenieDoRealizacji(Zlecenie zlecenie){

	}

	public Zlecenie Zlecenie{
		get{
			return zlecenie;
		}
		set{
			zlecenie = value;
		}
	}

}//end Ster_WybierzZlecenieZListyDostêpnychZleceñ