///////////////////////////////////////////////////////////
//  FormularzKierownika_WygenerujRaport.cs
//  Implementation of the Class FormularzKierownika_WygenerujRaport
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:08:32
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_WygenerujRaport {

	private Ciê¿arówka ciê¿arówka;
	private Kierowca kierowca;
	private Rodzaj raportu rodzaj;
	private Szablon raportu szablon;
	private Zlecenie zlecenie;

	public FormularzKierownika_WygenerujRaport(){

	}

	~FormularzKierownika_WygenerujRaport(){

	}

	public void generujRaport(){

	}

	/// 
	/// <param name="szablon"></param>
	public void potwierdŸ(Szablon raportu szablon){

	}

	public Ster_WygenerujRaport Ster_WygenerujRaport{
		get{
			return m_Ster_WygenerujRaport;
		}
		set{
			m_Ster_WygenerujRaport = value;
		}
	}

	public void wyœwietlFormularzGenerowaniaRaportu(){

	}

	/// 
	/// <param name="raporty"></param>
	public void wyœwietlListêRaportów(Lista raportów raporty){

	}

	public void wyœwietlMenuRaportów(){

	}

	/// 
	/// <param name="raport"></param>
	public void wyœwietlRaport(Raport raport){

	}

}//end FormularzKierownika_WygenerujRaport