///////////////////////////////////////////////////////////
//  Ster_WygenerujRaport.cs
//  Implementation of the Class Ster_WygenerujRaport
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:17:28
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_WygenerujRaport {

	private Ciê¿arówka ciê¿arówka;
	private Kierowca kierowca;
	private Rodzaj raportu rodzaj;
	private Szablon raportu szablon;
	private Zlecenie zlecenie;

	public Ster_WygenerujRaport(){

	}

	~Ster_WygenerujRaport(){

	}

	public void generujRaport(){

	}

	public Lista raportów Lista raportów{
		get{
			return m_Lista raportów;
		}
		set{
			m_Lista raportów = value;
		}
	}

	public void pobierzListêRaportów(){

	}

	public Raport Raport{
		get{
			return m_Raport;
		}
		set{
			m_Raport = value;
		}
	}

}//end Ster_WygenerujRaport