/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 05-kwi-2024 21:57:23 				*/
/*  DBMS       : MSAccess 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

ALTER TABLE [Ciê¿arówka] DROP CONSTRAINT [FK_Ciê¿arówka_Pojazd]

ALTER TABLE [Ciê¿arówka] DROP CONSTRAINT [FK_Ciê¿arówka_przypisanie]

ALTER TABLE [Ciê¿arówka] DROP CONSTRAINT [FK_Ciê¿arówka_Pojazd]

ALTER TABLE [Dyspozytor] DROP CONSTRAINT [FK_Dyspozytor_Osoba]

ALTER TABLE [Dyspozytor] DROP CONSTRAINT [FK_Dyspozytor_zarz¹dza]

ALTER TABLE [Dyspozytor] DROP CONSTRAINT [FK_Dyspozytor_Osoba]

ALTER TABLE [Kierowca] DROP CONSTRAINT [FK_Kierowca_przechowuje]

ALTER TABLE [Kierowca] DROP CONSTRAINT [FK_Kierowca_Osoba]

ALTER TABLE [Kierowca] DROP CONSTRAINT [FK_Kierowca_Osoba]

ALTER TABLE [Kierownik] DROP CONSTRAINT [FK_Kierownik_Osoba]

ALTER TABLE [Kierownik] DROP CONSTRAINT [FK_Kierownik_Osoba]

ALTER TABLE [ListaKierowców] DROP CONSTRAINT [FK_Lista kierowców_zarz¹dza]

ALTER TABLE [ListaPojazdów] DROP CONSTRAINT [FK_Lista pojazdów_zarz¹dza]

ALTER TABLE [Naczepa] DROP CONSTRAINT [FK_Naczepa_przypisanie]

ALTER TABLE [Naczepa] DROP CONSTRAINT [FK_Naczepa_Pojazd]

ALTER TABLE [Naczepa] DROP CONSTRAINT [FK_Naczepa_Pojazd]

ALTER TABLE [Pojazd] DROP CONSTRAINT [FK_Pojazd_przechowuje]

ALTER TABLE [Po³o¿enieCiê¿arówki] DROP CONSTRAINT [FK_Po³o¿enie ciê¿arówki_przypisanie]

ALTER TABLE [PowiadomienieE-mail] DROP CONSTRAINT [FK_Powiadomienie e-mail_otrzymuje]

ALTER TABLE [PowiadomienieE-mail] DROP CONSTRAINT [FK_Powiadomienie e-mail_dotyczy]

ALTER TABLE [PunktDocelowy] DROP CONSTRAINT [FK_Punkt docelowy_sk³ada siê z]

ALTER TABLE [Raport] DROP CONSTRAINT [FK_Raport_generuje]

ALTER TABLE [Raport] DROP CONSTRAINT [FK_Raport_przechowuje]

ALTER TABLE [Raport] DROP CONSTRAINT [FK_Raport_generowany na podstawie]

ALTER TABLE [Spedytor] DROP CONSTRAINT [FK_Spedytor_Osoba]

ALTER TABLE [Spedytor] DROP CONSTRAINT [FK_Spedytor_Osoba]

ALTER TABLE [Towar] DROP CONSTRAINT [FK_Towar_dotyczy przewozu]

ALTER TABLE [ZdarzenieNaTrasie] DROP CONSTRAINT [FK_Zdarzenie na trasie_posiada]

ALTER TABLE [Zlecenie] DROP CONSTRAINT [FK_Zlecenie_przechowuje]

ALTER TABLE [Zlecenie] DROP CONSTRAINT [FK_Zlecenie_dodaje]

ALTER TABLE [Zlecenie] DROP CONSTRAINT [FK_Zlecenie_dotyczy]

/* Drop Tables */

DROP TABLE [Ciê¿arówka]

DROP TABLE [Dyspozytor]

DROP TABLE [Kierowca]

DROP TABLE [Kierownik]

DROP TABLE [ListaKierowców]

DROP TABLE [ListaPojazdów]

DROP TABLE [ListaRaportów]

DROP TABLE [ListaZleceñ]

DROP TABLE [Naczepa]

DROP TABLE [Osoba]

DROP TABLE [Pojazd]

DROP TABLE [Po³o¿enieCiê¿arówki]

DROP TABLE [PowiadomienieE-mail]

DROP TABLE [PunktDocelowy]

DROP TABLE [Raport]

DROP TABLE [Spedytor]

DROP TABLE [SzablonRaportu]

DROP TABLE [Towar]

DROP TABLE [Trasa]

DROP TABLE [ZdarzenieNaTrasie]

DROP TABLE [Zlecenie]

/* Create Tables */

CREATE TABLE [Ciê¿arówka]
(
	[HistoriaTankowania] varchar NULL,
	[Ciê¿arówkaID] Short NOT NULL,
	[KierowcaID] Short NULL
)

CREATE TABLE [Dyspozytor]
(
	[PrzyjêteZlecenia] varchar NULL,
	[DyspozytorID] Short NOT NULL,
	[ListaZleceñID] Short NOT NULL
)

CREATE TABLE [Kierowca]
(
	[HistoriaZleceñ] varchar NULL,
	[NumerKierowcy] varchar NULL,
	[KierowcaID] Short NOT NULL,
	[ListaKierowcówID] Short NULL
)

CREATE TABLE [Kierownik]
(
	[KierownikID] Short NOT NULL
)

CREATE TABLE [ListaKierowców]
(
	[ListaKierowcówID] Short NOT NULL,
	[KierownikID] Short NOT NULL
)

CREATE TABLE [ListaPojazdów]
(
	[ListaPojazdówID] Short NOT NULL,
	[KierownikID] Short NOT NULL
)

CREATE TABLE [ListaRaportów]
(
	[ListaRaportówID] Short NOT NULL
)

CREATE TABLE [ListaZleceñ]
(
	[ListaZleceñID] Short NOT NULL
)

CREATE TABLE [Naczepa]
(
	[NaczepaID] Short NOT NULL,
	[KierowcaID] Short NULL
)

CREATE TABLE [Osoba]
(
	[Email] varchar NULL,
	[Imiê] varchar NULL,
	[Nazwisko] varchar NULL,
	[Pesel] varchar NULL,
	[Telefon] varchar NULL,
	[Uprawnienia] varchar NULL,
	[OsobaID] Short NOT NULL
)

CREATE TABLE [Pojazd]
(
	[Marka] varchar NULL,
	[Model] varchar NULL,
	[NumerRejestracyjny] varchar NULL,
	[Przebieg] varchar NULL,
	[Status] Short NULL,
	[PojazdID] Short NOT NULL,
	[ListaPojazdówID] Short NULL
)

CREATE TABLE [Po³o¿enieCiê¿arówki]
(
	[Czas] DateTime NULL,
	[Wspó³rzêdne] varchar NULL,
	[Po³o¿enieCiê¿arówkiID] Short NOT NULL,
	[ZdarzenieNaTrasieID] Short NOT NULL
)

CREATE TABLE [PowiadomienieE-mail]
(
	[CzasAkceptacjiZlecenia] DateTime NULL,
	[Status] Short NULL,
	[PowiadomienieE-mailID] Short NOT NULL,
	[KierowcaID] Short NULL,
	[ZlecenieID] Short NULL
)

CREATE TABLE [PunktDocelowy]
(
	[Nazwa] varchar NULL,
	[Odwiedzony] Byte NULL,
	[Wspó³rzêdne] varchar NULL,
	[PunktDocelowyID] Short NOT NULL,
	[TrasaID] Short NOT NULL
)

CREATE TABLE [Raport]
(
	[Autor] varchar NULL,
	[CzasWygenerowania] DateTime NULL,
	[Rodzaj] Short NULL,
	[RaportID] Short NOT NULL,
	[KierownikID] Short NULL,
	[ListaRaportówID] Short NULL,
	[SzablonRaportuID] Short NULL
)

CREATE TABLE [Spedytor]
(
	[DodaneZlecenia] varchar NULL,
	[FirmaSpedycyjna] varchar NULL,
	[SpedytorID] Short NOT NULL
)

CREATE TABLE [SzablonRaportu]
(
	[Struktura] Short NULL,
	[Styl] Short NULL,
	[SzablonRaportuID] Short NOT NULL
)

CREATE TABLE [Towar]
(
	[Iloœæ] Short NULL,
	[Jednostka] varchar NULL,
	[Nazwa] varchar NULL,
	[TowarID] Short NOT NULL,
	[ZlecenieID] Short NOT NULL
)

CREATE TABLE [Trasa]
(
	[CzasWyjazdu] DateTime NULL,
	[CzasZakoñczenia] DateTime NULL,
	[D³ugoœæ] Double NULL,
	[TrasaID] Short NOT NULL
)

CREATE TABLE [ZdarzenieNaTrasie]
(
	[Opis] varchar NULL,
	[Rodzaj] Short NULL,
	[ZdarzenieNaTrasieID] Short NOT NULL,
	[TrasaID] Short NULL
)

CREATE TABLE [Zlecenie]
(
	[CzasDodania] DateTime NULL,
	[CzasPrzyjêciaDoRealizacji] DateTime NULL,
	[CzasUkoñczenia] DateTime NULL,
	[Id] Short NULL,
	[NazwaKlienta] varchar NULL,
	[Status] Short NULL,
	[ZlecenieID] Short NOT NULL,
	[ListaZleceñID] Short NULL,
	[SpedytorID] Short NULL,
	[TrasaID] Short NULL
)

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Ciê¿arówka] ADD CONSTRAINT [PK_Ciê¿arówka]
	PRIMARY KEY ([Ciê¿arówkaID])

CREATE INDEX [IX_Ciê¿arówka] ON [Ciê¿arówka] ([Ciê¿arówkaID] ASC)

ALTER TABLE [Dyspozytor] ADD CONSTRAINT [PK_Dyspozytor]
	PRIMARY KEY ([DyspozytorID])

ALTER TABLE [Kierowca] ADD CONSTRAINT [PK_Kierowca]
	PRIMARY KEY ([KierowcaID])

CREATE INDEX [IX_Kierowca] ON [Kierowca] ([KierowcaID] ASC)

CREATE INDEX [IX_NumerKierowcy] ON [Kierowca] ([NumerKierowcy] ASC)

ALTER TABLE [Kierownik] ADD CONSTRAINT [PK_Kierownik]
	PRIMARY KEY ([KierownikID])

ALTER TABLE [ListaKierowców] ADD CONSTRAINT [PK_ListaKierowców]
	PRIMARY KEY ([ListaKierowcówID])

ALTER TABLE [ListaPojazdów] ADD CONSTRAINT [PK_ListaPojazdów]
	PRIMARY KEY ([ListaPojazdówID])

ALTER TABLE [ListaRaportów] ADD CONSTRAINT [PK_ListaRaportów]
	PRIMARY KEY ([ListaRaportówID])

ALTER TABLE [ListaZleceñ] ADD CONSTRAINT [PK_ListaZleceñ]
	PRIMARY KEY ([ListaZleceñID])

ALTER TABLE [Naczepa] ADD CONSTRAINT [PK_Naczepa]
	PRIMARY KEY ([NaczepaID])

CREATE INDEX [IX_Naczepa] ON [Naczepa] ([NaczepaID] ASC)

ALTER TABLE [Osoba] ADD CONSTRAINT [PK_Osoba]
	PRIMARY KEY ([OsobaID])

CREATE INDEX [IX_Imiê] ON [Osoba] ([Imiê] ASC)

CREATE INDEX [IX_Nazwisko] ON [Osoba] ([Nazwisko] ASC)

ALTER TABLE [Pojazd] ADD CONSTRAINT [PK_Pojazd]
	PRIMARY KEY ([PojazdID])

CREATE INDEX [IX_Pojazd] ON [Pojazd] ([PojazdID] ASC)

ALTER TABLE [Po³o¿enieCiê¿arówki] ADD CONSTRAINT [PK_Po³o¿enieCiê¿arówki]
	PRIMARY KEY ([Po³o¿enieCiê¿arówkiID])

ALTER TABLE [PowiadomienieE-mail] ADD CONSTRAINT [PK_PowiadomienieE-mail]
	PRIMARY KEY ([PowiadomienieE-mailID])

ALTER TABLE [PunktDocelowy] ADD CONSTRAINT [PK_PunktDocelowy]
	PRIMARY KEY ([PunktDocelowyID])

CREATE INDEX [IX_PunktDocelowy] ON [PunktDocelowy] ([PunktDocelowyID] ASC)

ALTER TABLE [Raport] ADD CONSTRAINT [PK_Raport]
	PRIMARY KEY ([RaportID])

ALTER TABLE [Spedytor] ADD CONSTRAINT [PK_Spedytor]
	PRIMARY KEY ([SpedytorID])

CREATE INDEX [IX_Spedytor] ON [Spedytor] ([SpedytorID] ASC)

ALTER TABLE [SzablonRaportu] ADD CONSTRAINT [PK_SzablonRaportu]
	PRIMARY KEY ([SzablonRaportuID])

ALTER TABLE [Towar] ADD CONSTRAINT [PK_Towar]
	PRIMARY KEY ([TowarID])

ALTER TABLE [Trasa] ADD CONSTRAINT [PK_Trasa]
	PRIMARY KEY ([TrasaID])

ALTER TABLE [ZdarzenieNaTrasie] ADD CONSTRAINT [PK_ZdarzenieNaTrasie]
	PRIMARY KEY ([ZdarzenieNaTrasieID])

ALTER TABLE [Zlecenie] ADD CONSTRAINT [PK_Zlecenie]
	PRIMARY KEY ([ZlecenieID])

CREATE INDEX [IX_Zlecenie] ON [Zlecenie] ([ZlecenieID] ASC)

CREATE INDEX [IX_CzasUkoñczenia] ON [Zlecenie] ([CzasUkoñczenia] ASC)

/* Create Foreign Key Constraints */

ALTER TABLE [Ciê¿arówka] ADD CONSTRAINT [FK_Ciê¿arówka_Pojazd]
	FOREIGN KEY ([Ciê¿arówkaID]) REFERENCES [Pojazd] ([PojazdID])

ALTER TABLE [Ciê¿arówka] ADD CONSTRAINT [FK_Ciê¿arówka_przypisanie]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Kierowca] ([KierowcaID])

ALTER TABLE [Ciê¿arówka] ADD CONSTRAINT [FK_Ciê¿arówka_Pojazd]
	FOREIGN KEY ([Ciê¿arówkaID]) REFERENCES [Pojazd] ([PojazdID])

ALTER TABLE [Dyspozytor] ADD CONSTRAINT [FK_Dyspozytor_Osoba]
	FOREIGN KEY ([DyspozytorID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Dyspozytor] ADD CONSTRAINT [FK_Dyspozytor_zarz¹dza]
	FOREIGN KEY ([ListaZleceñID]) REFERENCES [ListaZleceñ] ([ListaZleceñID])

ALTER TABLE [Dyspozytor] ADD CONSTRAINT [FK_Dyspozytor_Osoba]
	FOREIGN KEY ([DyspozytorID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Kierowca] ADD CONSTRAINT [FK_Kierowca_przechowuje]
	FOREIGN KEY ([ListaKierowcówID]) REFERENCES [ListaKierowców] ([ListaKierowcówID])

ALTER TABLE [Kierowca] ADD CONSTRAINT [FK_Kierowca_Osoba]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Kierowca] ADD CONSTRAINT [FK_Kierowca_Osoba]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Kierownik] ADD CONSTRAINT [FK_Kierownik_Osoba]
	FOREIGN KEY ([KierownikID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Kierownik] ADD CONSTRAINT [FK_Kierownik_Osoba]
	FOREIGN KEY ([KierownikID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [ListaKierowców] ADD CONSTRAINT [FK_Lista kierowców_zarz¹dza]
	FOREIGN KEY ([KierownikID]) REFERENCES [Kierownik] ([KierownikID])

ALTER TABLE [ListaPojazdów] ADD CONSTRAINT [FK_Lista pojazdów_zarz¹dza]
	FOREIGN KEY ([KierownikID]) REFERENCES [Kierownik] ([KierownikID])

ALTER TABLE [Naczepa] ADD CONSTRAINT [FK_Naczepa_przypisanie]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Kierowca] ([KierowcaID])

ALTER TABLE [Naczepa] ADD CONSTRAINT [FK_Naczepa_Pojazd]
	FOREIGN KEY ([NaczepaID]) REFERENCES [Pojazd] ([PojazdID])

ALTER TABLE [Naczepa] ADD CONSTRAINT [FK_Naczepa_Pojazd]
	FOREIGN KEY ([NaczepaID]) REFERENCES [Pojazd] ([PojazdID])

ALTER TABLE [Pojazd] ADD CONSTRAINT [FK_Pojazd_przechowuje]
	FOREIGN KEY ([ListaPojazdówID]) REFERENCES [ListaPojazdów] ([ListaPojazdówID])

ALTER TABLE [Po³o¿enieCiê¿arówki] ADD CONSTRAINT [FK_Po³o¿enie ciê¿arówki_przypisanie]
	FOREIGN KEY ([ZdarzenieNaTrasieID]) REFERENCES [ZdarzenieNaTrasie] ([ZdarzenieNaTrasieID])

ALTER TABLE [PowiadomienieE-mail] ADD CONSTRAINT [FK_Powiadomienie e-mail_otrzymuje]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Kierowca] ([KierowcaID])

ALTER TABLE [PowiadomienieE-mail] ADD CONSTRAINT [FK_Powiadomienie e-mail_dotyczy]
	FOREIGN KEY ([ZlecenieID]) REFERENCES [Zlecenie] ([ZlecenieID])

ALTER TABLE [PunktDocelowy] ADD CONSTRAINT [FK_Punkt docelowy_sk³ada siê z]
	FOREIGN KEY ([TrasaID]) REFERENCES [Trasa] ([TrasaID])

ALTER TABLE [Raport] ADD CONSTRAINT [FK_Raport_generuje]
	FOREIGN KEY ([KierownikID]) REFERENCES [Kierownik] ([KierownikID])

ALTER TABLE [Raport] ADD CONSTRAINT [FK_Raport_przechowuje]
	FOREIGN KEY ([ListaRaportówID]) REFERENCES [ListaRaportów] ([ListaRaportówID])

ALTER TABLE [Raport] ADD CONSTRAINT [FK_Raport_generowany na podstawie]
	FOREIGN KEY ([SzablonRaportuID]) REFERENCES [SzablonRaportu] ([SzablonRaportuID])

ALTER TABLE [Spedytor] ADD CONSTRAINT [FK_Spedytor_Osoba]
	FOREIGN KEY ([SpedytorID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Spedytor] ADD CONSTRAINT [FK_Spedytor_Osoba]
	FOREIGN KEY ([SpedytorID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Towar] ADD CONSTRAINT [FK_Towar_dotyczy przewozu]
	FOREIGN KEY ([ZlecenieID]) REFERENCES [Zlecenie] ([ZlecenieID])

ALTER TABLE [ZdarzenieNaTrasie] ADD CONSTRAINT [FK_Zdarzenie na trasie_posiada]
	FOREIGN KEY ([TrasaID]) REFERENCES [Trasa] ([TrasaID])

ALTER TABLE [Zlecenie] ADD CONSTRAINT [FK_Zlecenie_przechowuje]
	FOREIGN KEY ([ListaZleceñID]) REFERENCES [ListaZleceñ] ([ListaZleceñID])

ALTER TABLE [Zlecenie] ADD CONSTRAINT [FK_Zlecenie_dodaje]
	FOREIGN KEY ([SpedytorID]) REFERENCES [Spedytor] ([SpedytorID])

ALTER TABLE [Zlecenie] ADD CONSTRAINT [FK_Zlecenie_dotyczy]
	FOREIGN KEY ([TrasaID]) REFERENCES [Trasa] ([TrasaID])
