/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 05-kwi-2024 21:09:37 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ciê¿arówka_Pojazd]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ciê¿arówka] DROP CONSTRAINT [FK_Ciê¿arówka_Pojazd]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ciê¿arówka_przypisanie]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ciê¿arówka] DROP CONSTRAINT [FK_Ciê¿arówka_przypisanie]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ciê¿arówka_Pojazd]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ciê¿arówka] DROP CONSTRAINT [FK_Ciê¿arówka_Pojazd]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Dyspozytor_Osoba]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Dyspozytor] DROP CONSTRAINT [FK_Dyspozytor_Osoba]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Dyspozytor_zarz¹dza]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Dyspozytor] DROP CONSTRAINT [FK_Dyspozytor_zarz¹dza]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Dyspozytor_Osoba]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Dyspozytor] DROP CONSTRAINT [FK_Dyspozytor_Osoba]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Kierowca_przechowuje]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kierowca] DROP CONSTRAINT [FK_Kierowca_przechowuje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Kierowca_Osoba]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kierowca] DROP CONSTRAINT [FK_Kierowca_Osoba]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Kierowca_Osoba]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kierowca] DROP CONSTRAINT [FK_Kierowca_Osoba]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Kierownik_Osoba]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kierownik] DROP CONSTRAINT [FK_Kierownik_Osoba]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Kierownik_Osoba]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kierownik] DROP CONSTRAINT [FK_Kierownik_Osoba]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Lista kierowców_zarz¹dza]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ListaKierowców] DROP CONSTRAINT [FK_Lista kierowców_zarz¹dza]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Lista pojazdów_zarz¹dza]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ListaPojazdów] DROP CONSTRAINT [FK_Lista pojazdów_zarz¹dza]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Naczepa_przypisanie]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Naczepa] DROP CONSTRAINT [FK_Naczepa_przypisanie]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Naczepa_Pojazd]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Naczepa] DROP CONSTRAINT [FK_Naczepa_Pojazd]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Naczepa_Pojazd]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Naczepa] DROP CONSTRAINT [FK_Naczepa_Pojazd]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pojazd_przechowuje]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pojazd] DROP CONSTRAINT [FK_Pojazd_przechowuje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Po³o¿enie ciê¿arówki_przypisanie]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Po³o¿enieCiê¿arówki] DROP CONSTRAINT [FK_Po³o¿enie ciê¿arówki_przypisanie]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Powiadomienie e-mail_otrzymuje]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [PowiadomienieE-mail] DROP CONSTRAINT [FK_Powiadomienie e-mail_otrzymuje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Powiadomienie e-mail_dotyczy]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [PowiadomienieE-mail] DROP CONSTRAINT [FK_Powiadomienie e-mail_dotyczy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Punkt docelowy_sk³ada siê z]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [PunktDocelowy] DROP CONSTRAINT [FK_Punkt docelowy_sk³ada siê z]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Raport_generuje]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Raport] DROP CONSTRAINT [FK_Raport_generuje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Raport_przechowuje]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Raport] DROP CONSTRAINT [FK_Raport_przechowuje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Raport_generowany na podstawie]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Raport] DROP CONSTRAINT [FK_Raport_generowany na podstawie]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Spedytor_Osoba]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Spedytor] DROP CONSTRAINT [FK_Spedytor_Osoba]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Spedytor_Osoba]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Spedytor] DROP CONSTRAINT [FK_Spedytor_Osoba]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Towar_dotyczy przewozu]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Towar] DROP CONSTRAINT [FK_Towar_dotyczy przewozu]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Zdarzenie na trasie_posiada]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ZdarzenieNaTrasie] DROP CONSTRAINT [FK_Zdarzenie na trasie_posiada]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Zlecenie_przechowuje]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Zlecenie] DROP CONSTRAINT [FK_Zlecenie_przechowuje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Zlecenie_dodaje]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Zlecenie] DROP CONSTRAINT [FK_Zlecenie_dodaje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Zlecenie_dotyczy]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Zlecenie] DROP CONSTRAINT [FK_Zlecenie_dotyczy]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Ciê¿arówka]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Ciê¿arówka]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Dyspozytor]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Dyspozytor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Kierowca]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Kierowca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Kierownik]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Kierownik]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ListaKierowców]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ListaKierowców]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ListaPojazdów]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ListaPojazdów]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ListaRaportów]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ListaRaportów]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ListaZleceñ]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ListaZleceñ]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Naczepa]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Naczepa]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Osoba]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Osoba]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pojazd]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pojazd]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Po³o¿enieCiê¿arówki]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Po³o¿enieCiê¿arówki]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[PowiadomienieE-mail]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [PowiadomienieE-mail]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[PunktDocelowy]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [PunktDocelowy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Raport]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Raport]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Spedytor]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Spedytor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[SzablonRaportu]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [SzablonRaportu]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Towar]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Towar]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Trasa]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Trasa]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ZdarzenieNaTrasie]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ZdarzenieNaTrasie]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Zlecenie]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Zlecenie]
GO

/* Create Tables */

CREATE TABLE [Ciê¿arówka]
(
	[HistoriaTankowania] varchar NULL,
	[Ciê¿arówkaID] varchar NOT NULL,
	[KierowcaID] Integer NULL
)
GO

CREATE TABLE [Dyspozytor]
(
	[PrzyjêteZlecenia] varchar NULL,
	[DyspozytorID] varchar NOT NULL,
	[ListaZleceñID] Integer NOT NULL
)
GO

CREATE TABLE [Kierowca]
(
	[HistoriaZleceñ] varchar NULL,
	[NumerKierowcy] varchar NULL,
	[KierowcaID] varchar NOT NULL,
	[ListaKierowcówID] Integer NULL
)
GO

CREATE TABLE [Kierownik]
(
	[KierownikID] varchar NOT NULL
)
GO

CREATE TABLE [ListaKierowców]
(
	[ListaKierowcówID] varchar NOT NULL,
	[KierownikID] Integer NOT NULL
)
GO

CREATE TABLE [ListaPojazdów]
(
	[ListaPojazdówID] varchar NOT NULL,
	[KierownikID] Integer NOT NULL
)
GO

CREATE TABLE [ListaRaportów]
(
	[ListaRaportówID] varchar NOT NULL
)
GO

CREATE TABLE [ListaZleceñ]
(
	[ListaZleceñID] varchar NOT NULL
)
GO

CREATE TABLE [Naczepa]
(
	[NaczepaID] varchar NOT NULL,
	[KierowcaID] Integer NULL
)
GO

CREATE TABLE [Osoba]
(
	[Email] varchar NULL,
	[Imiê] varchar NULL,
	[Nazwisko] varchar NULL,
	[Pesel] varchar NULL,
	[Telefon] varchar NULL,
	[Uprawnienia] varchar NULL,
	[OsobaID] varchar NOT NULL
)
GO

CREATE TABLE [Pojazd]
(
	[Marka] varchar NULL,
	[Model] varchar NULL,
	[NumerRejestracyjny] varchar NULL,
	[Przebieg] varchar NULL,
	[Status] varchar NULL,
	[PojazdID] varchar NOT NULL,
	[ListaPojazdówID] Integer NULL
)
GO

CREATE TABLE [Po³o¿enieCiê¿arówki]
(
	[Czas] varchar NULL,
	[Wspó³rzêdne] varchar NULL,
	[Po³o¿enieCiê¿arówkiID] varchar NOT NULL,
	[ZdarzenieNaTrasieID] Integer NOT NULL
)
GO

CREATE TABLE [PowiadomienieE-mail]
(
	[CzasAkceptacjiZlecenia] varchar NULL,
	[Status] varchar NULL,
	[PowiadomienieE-mailID] varchar NOT NULL,
	[KierowcaID] Integer NULL,
	[ZlecenieID] Integer NULL
)
GO

CREATE TABLE [PunktDocelowy]
(
	[Nazwa] varchar NULL,
	[Odwiedzony] varchar NULL,
	[Wspó³rzêdne] varchar NULL,
	[PunktDocelowyID] varchar NOT NULL,
	[TrasaID] Integer NOT NULL
)
GO

CREATE TABLE [Raport]
(
	[Autor] varchar NULL,
	[CzasWygenerowania] varchar NULL,
	[Rodzaj] varchar NULL,
	[RaportID] varchar NOT NULL,
	[KierownikID] Integer NULL,
	[ListaRaportówID] Integer NULL,
	[SzablonRaportuID] Integer NULL
)
GO

CREATE TABLE [Spedytor]
(
	[DodaneZlecenia] varchar NULL,
	[FirmaSpedycyjna] varchar NULL,
	[SpedytorID] varchar NOT NULL
)
GO

CREATE TABLE [SzablonRaportu]
(
	[Struktura] varchar NULL,
	[Styl] varchar NULL,
	[SzablonRaportuID] varchar NOT NULL
)
GO

CREATE TABLE [Towar]
(
	[Iloœæ] varchar NULL,
	[Jednostka] varchar NULL,
	[Nazwa] varchar NULL,
	[TowarID] varchar NOT NULL,
	[ZlecenieID] Integer NOT NULL
)
GO

CREATE TABLE [Trasa]
(
	[CzasWyjazdu] varchar NULL,
	[CzasZakoñczenia] varchar NULL,
	[D³ugoœæ] varchar NULL,
	[TrasaID] varchar NOT NULL
)
GO

CREATE TABLE [ZdarzenieNaTrasie]
(
	[Opis] varchar NULL,
	[Rodzaj] varchar NULL,
	[ZdarzenieNaTrasieID] varchar NOT NULL,
	[TrasaID] Integer NULL
)
GO

CREATE TABLE [Zlecenie]
(
	[CzasDodania] varchar NULL,
	[CzasPrzyjêciaDoRealizacji] varchar NULL,
	[CzasUkoñczenia] varchar NULL,
	[Id] varchar NULL,
	[NazwaKlienta] varchar NULL,
	[Status] varchar NULL,
	[ZlecenieID] varchar NOT NULL,
	[ListaZleceñID] Integer NULL,
	[SpedytorID] Integer NULL,
	[TrasaID] Integer NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Ciê¿arówka] 
 ADD CONSTRAINT [PK_Ciê¿arówka]
	PRIMARY KEY CLUSTERED ([Ciê¿arówkaID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Ciê¿arówka] 
 ON [Ciê¿arówka] ([Ciê¿arówkaID] ASC)
GO

ALTER TABLE [Dyspozytor] 
 ADD CONSTRAINT [PK_Dyspozytor]
	PRIMARY KEY CLUSTERED ([DyspozytorID] ASC)
GO

ALTER TABLE [Kierowca] 
 ADD CONSTRAINT [PK_Kierowca]
	PRIMARY KEY CLUSTERED ([KierowcaID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Kierowca] 
 ON [Kierowca] ([KierowcaID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_NumerKierowcy] 
 ON [Kierowca] ([NumerKierowcy] ASC)
GO

ALTER TABLE [Kierownik] 
 ADD CONSTRAINT [PK_Kierownik]
	PRIMARY KEY CLUSTERED ([KierownikID] ASC)
GO

ALTER TABLE [ListaKierowców] 
 ADD CONSTRAINT [PK_ListaKierowców]
	PRIMARY KEY CLUSTERED ([ListaKierowcówID] ASC)
GO

ALTER TABLE [ListaPojazdów] 
 ADD CONSTRAINT [PK_ListaPojazdów]
	PRIMARY KEY CLUSTERED ([ListaPojazdówID] ASC)
GO

ALTER TABLE [ListaRaportów] 
 ADD CONSTRAINT [PK_ListaRaportów]
	PRIMARY KEY CLUSTERED ([ListaRaportówID] ASC)
GO

ALTER TABLE [ListaZleceñ] 
 ADD CONSTRAINT [PK_ListaZleceñ]
	PRIMARY KEY CLUSTERED ([ListaZleceñID] ASC)
GO

ALTER TABLE [Naczepa] 
 ADD CONSTRAINT [PK_Naczepa]
	PRIMARY KEY CLUSTERED ([NaczepaID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Naczepa] 
 ON [Naczepa] ([NaczepaID] ASC)
GO

ALTER TABLE [Osoba] 
 ADD CONSTRAINT [PK_Osoba]
	PRIMARY KEY CLUSTERED ([OsobaID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Imiê] 
 ON [Osoba] ([Imiê] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Nazwisko] 
 ON [Osoba] ([Nazwisko] ASC)
GO

ALTER TABLE [Pojazd] 
 ADD CONSTRAINT [PK_Pojazd]
	PRIMARY KEY CLUSTERED ([PojazdID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Pojazd] 
 ON [Pojazd] ([PojazdID] ASC)
GO

ALTER TABLE [Po³o¿enieCiê¿arówki] 
 ADD CONSTRAINT [PK_Po³o¿enieCiê¿arówki]
	PRIMARY KEY CLUSTERED ([Po³o¿enieCiê¿arówkiID] ASC)
GO

ALTER TABLE [PowiadomienieE-mail] 
 ADD CONSTRAINT [PK_PowiadomienieE-mail]
	PRIMARY KEY CLUSTERED ([PowiadomienieE-mailID] ASC)
GO

ALTER TABLE [PunktDocelowy] 
 ADD CONSTRAINT [PK_PunktDocelowy]
	PRIMARY KEY CLUSTERED ([PunktDocelowyID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_PunktDocelowy] 
 ON [PunktDocelowy] ([PunktDocelowyID] ASC)
GO

ALTER TABLE [Raport] 
 ADD CONSTRAINT [PK_Raport]
	PRIMARY KEY CLUSTERED ([RaportID] ASC)
GO

ALTER TABLE [Spedytor] 
 ADD CONSTRAINT [PK_Spedytor]
	PRIMARY KEY CLUSTERED ([SpedytorID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Spedytor] 
 ON [Spedytor] ([SpedytorID] ASC)
GO

ALTER TABLE [SzablonRaportu] 
 ADD CONSTRAINT [PK_SzablonRaportu]
	PRIMARY KEY CLUSTERED ([SzablonRaportuID] ASC)
GO

ALTER TABLE [Towar] 
 ADD CONSTRAINT [PK_Towar]
	PRIMARY KEY CLUSTERED ([TowarID] ASC)
GO

ALTER TABLE [Trasa] 
 ADD CONSTRAINT [PK_Trasa]
	PRIMARY KEY CLUSTERED ([TrasaID] ASC)
GO

ALTER TABLE [ZdarzenieNaTrasie] 
 ADD CONSTRAINT [PK_ZdarzenieNaTrasie]
	PRIMARY KEY CLUSTERED ([ZdarzenieNaTrasieID] ASC)
GO

ALTER TABLE [Zlecenie] 
 ADD CONSTRAINT [PK_Zlecenie]
	PRIMARY KEY CLUSTERED ([ZlecenieID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Zlecenie] 
 ON [Zlecenie] ([ZlecenieID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_CzasUkoñczenia] 
 ON [Zlecenie] ([CzasUkoñczenia] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Ciê¿arówka] ADD CONSTRAINT [FK_Ciê¿arówka_Pojazd]
	FOREIGN KEY ([Ciê¿arówkaID]) REFERENCES [Pojazd] ([PojazdID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Ciê¿arówka] ADD CONSTRAINT [FK_Ciê¿arówka_przypisanie]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Kierowca] ([KierowcaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Ciê¿arówka] ADD CONSTRAINT [FK_Ciê¿arówka_Pojazd]
	FOREIGN KEY ([Ciê¿arówkaID]) REFERENCES [Pojazd] ([PojazdID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Dyspozytor] ADD CONSTRAINT [FK_Dyspozytor_Osoba]
	FOREIGN KEY ([DyspozytorID]) REFERENCES [Osoba] ([OsobaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Dyspozytor] ADD CONSTRAINT [FK_Dyspozytor_zarz¹dza]
	FOREIGN KEY ([ListaZleceñID]) REFERENCES [ListaZleceñ] ([ListaZleceñID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Dyspozytor] ADD CONSTRAINT [FK_Dyspozytor_Osoba]
	FOREIGN KEY ([DyspozytorID]) REFERENCES [Osoba] ([OsobaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kierowca] ADD CONSTRAINT [FK_Kierowca_przechowuje]
	FOREIGN KEY ([ListaKierowcówID]) REFERENCES [ListaKierowców] ([ListaKierowcówID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kierowca] ADD CONSTRAINT [FK_Kierowca_Osoba]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Osoba] ([OsobaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kierowca] ADD CONSTRAINT [FK_Kierowca_Osoba]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Osoba] ([OsobaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kierownik] ADD CONSTRAINT [FK_Kierownik_Osoba]
	FOREIGN KEY ([KierownikID]) REFERENCES [Osoba] ([OsobaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kierownik] ADD CONSTRAINT [FK_Kierownik_Osoba]
	FOREIGN KEY ([KierownikID]) REFERENCES [Osoba] ([OsobaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ListaKierowców] ADD CONSTRAINT [FK_Lista kierowców_zarz¹dza]
	FOREIGN KEY ([KierownikID]) REFERENCES [Kierownik] ([KierownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ListaPojazdów] ADD CONSTRAINT [FK_Lista pojazdów_zarz¹dza]
	FOREIGN KEY ([KierownikID]) REFERENCES [Kierownik] ([KierownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Naczepa] ADD CONSTRAINT [FK_Naczepa_przypisanie]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Kierowca] ([KierowcaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Naczepa] ADD CONSTRAINT [FK_Naczepa_Pojazd]
	FOREIGN KEY ([NaczepaID]) REFERENCES [Pojazd] ([PojazdID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Naczepa] ADD CONSTRAINT [FK_Naczepa_Pojazd]
	FOREIGN KEY ([NaczepaID]) REFERENCES [Pojazd] ([PojazdID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pojazd] ADD CONSTRAINT [FK_Pojazd_przechowuje]
	FOREIGN KEY ([ListaPojazdówID]) REFERENCES [ListaPojazdów] ([ListaPojazdówID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Po³o¿enieCiê¿arówki] ADD CONSTRAINT [FK_Po³o¿enie ciê¿arówki_przypisanie]
	FOREIGN KEY ([ZdarzenieNaTrasieID]) REFERENCES [ZdarzenieNaTrasie] ([ZdarzenieNaTrasieID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PowiadomienieE-mail] ADD CONSTRAINT [FK_Powiadomienie e-mail_otrzymuje]
	FOREIGN KEY ([KierowcaID]) REFERENCES [Kierowca] ([KierowcaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PowiadomienieE-mail] ADD CONSTRAINT [FK_Powiadomienie e-mail_dotyczy]
	FOREIGN KEY ([ZlecenieID]) REFERENCES [Zlecenie] ([ZlecenieID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PunktDocelowy] ADD CONSTRAINT [FK_Punkt docelowy_sk³ada siê z]
	FOREIGN KEY ([TrasaID]) REFERENCES [Trasa] ([TrasaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Raport] ADD CONSTRAINT [FK_Raport_generuje]
	FOREIGN KEY ([KierownikID]) REFERENCES [Kierownik] ([KierownikID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Raport] ADD CONSTRAINT [FK_Raport_przechowuje]
	FOREIGN KEY ([ListaRaportówID]) REFERENCES [ListaRaportów] ([ListaRaportówID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Raport] ADD CONSTRAINT [FK_Raport_generowany na podstawie]
	FOREIGN KEY ([SzablonRaportuID]) REFERENCES [SzablonRaportu] ([SzablonRaportuID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Spedytor] ADD CONSTRAINT [FK_Spedytor_Osoba]
	FOREIGN KEY ([SpedytorID]) REFERENCES [Osoba] ([OsobaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Spedytor] ADD CONSTRAINT [FK_Spedytor_Osoba]
	FOREIGN KEY ([SpedytorID]) REFERENCES [Osoba] ([OsobaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Towar] ADD CONSTRAINT [FK_Towar_dotyczy przewozu]
	FOREIGN KEY ([ZlecenieID]) REFERENCES [Zlecenie] ([ZlecenieID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ZdarzenieNaTrasie] ADD CONSTRAINT [FK_Zdarzenie na trasie_posiada]
	FOREIGN KEY ([TrasaID]) REFERENCES [Trasa] ([TrasaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Zlecenie] ADD CONSTRAINT [FK_Zlecenie_przechowuje]
	FOREIGN KEY ([ListaZleceñID]) REFERENCES [ListaZleceñ] ([ListaZleceñID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Zlecenie] ADD CONSTRAINT [FK_Zlecenie_dodaje]
	FOREIGN KEY ([SpedytorID]) REFERENCES [Spedytor] ([SpedytorID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Zlecenie] ADD CONSTRAINT [FK_Zlecenie_dotyczy]
	FOREIGN KEY ([TrasaID]) REFERENCES [Trasa] ([TrasaID]) ON DELETE No Action ON UPDATE No Action
GO
