///////////////////////////////////////////////////////////
//  FormularzKierowcy_ZarejestrujWyjazd.cs
//  Implementation of the Class FormularzKierowcy_ZarejestrujWyjazd
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:02:37
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierowcy_ZarejestrujWyjazd {

	private Datetime czas;
	private Kierowca kierowca;
	private Zlecenie zlecenie;

	public FormularzKierowcy_ZarejestrujWyjazd(){

	}

	~FormularzKierowcy_ZarejestrujWyjazd(){

	}

	public Ster_ZarejestrujWyjazd Ster_ZarejestrujWyjazd{
		get{
			return m_Ster_ZarejestrujWyjazd;
		}
		set{
			m_Ster_ZarejestrujWyjazd = value;
		}
	}

	public void wyœwietlKomunikatOZarejestrowaniuWyjazdu(){

	}

	public void zarejestrujWyjazd(){

	}

}//end FormularzKierowcy_ZarejestrujWyjazd