///////////////////////////////////////////////////////////
//  FormularzKierowcy_ZarejestrujZakoñczenieRealizacjiZlecenia.cs
//  Implementation of the Class FormularzKierowcy_ZarejestrujZakoñczenieRealizacjiZlecenia
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:02:41
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierowcy_ZarejestrujZakoñczenieRealizacjiZlecenia {

	private Datetime czas;
	private Kierowca kierowca;
	private Zlecenie zlecenie;

	public FormularzKierowcy_ZarejestrujZakoñczenieRealizacjiZlecenia(){

	}

	~FormularzKierowcy_ZarejestrujZakoñczenieRealizacjiZlecenia(){

	}

	public Ster_ZarejestrujZakoñczenieRealizacjiZlecenia Ster_ZarejestrujZakoñczenieRealizacjiZlecenia{
		get{
			return m_Ster_ZarejestrujZakoñczenieRealizacjiZlecenia;
		}
		set{
			m_Ster_ZarejestrujZakoñczenieRealizacjiZlecenia = value;
		}
	}

	public void wyœwietlKomunikatOZarejestrowaniuZakoñczeniaZlecenia(){

	}

	public void zarejestrujKoniecZlecenia(){

	}

}//end FormularzKierowcy_ZarejestrujZakoñczenieRealizacjiZlecenia