///////////////////////////////////////////////////////////
//  FormularzKierowcy_ZarejestrujZdarzenieNaTrasie.cs
//  Implementation of the Class FormularzKierowcy_ZarejestrujZdarzenieNaTrasie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:02:44
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierowcy_ZarejestrujZdarzenieNaTrasie {

	private Kierowca kierowca;
	private Po³o¿enie ciê¿arówki po³o¿enie ciê¿arówki;
	private Zdarzenie na trasie zdarzenie na trasie;
	private Zlecenie zlecenie;

	public FormularzKierowcy_ZarejestrujZdarzenieNaTrasie(){

	}

	~FormularzKierowcy_ZarejestrujZdarzenieNaTrasie(){

	}

	public Ster_ZarejestrujZdarzenieNaTrasie Ster_ZarejestrujZdarzenieNaTrasie{
		get{
			return m_Ster_ZarejestrujZdarzenieNaTrasie;
		}
		set{
			m_Ster_ZarejestrujZdarzenieNaTrasie = value;
		}
	}

	/// 
	/// <param name="zdarzenie"></param>
	/// <param name="trasa"></param>
	public void utwórzZdarzenie(Zdarzenie na trasie zdarzenie, Trasa trasa){

	}

	/// 
	/// <param name="kategoria"></param>
	public void wybierzKategoriêZdarzenia(string kategoria){

	}

	/// 
	/// <param name="trasa"></param>
	public void wyœwietlFormularzRejestrowaniaZdarzenia(Trasa trasa){

	}

	/// 
	/// <param name="kategoria"></param>
	public void wyœwietlSzablonDlaKategoriiZdarzenia(string kategoria){

	}

	/// 
	/// <param name="trasa"></param>
	public void zarejestrujZdarzenie(Trasa trasa){

	}

}//end FormularzKierowcy_ZarejestrujZdarzenieNaTrasie