///////////////////////////////////////////////////////////
//  FormularzKierowcy_PoinformujOProblemie.cs
//  Implementation of the Class FormularzKierowcy_PoinformujOProblemie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:02:29
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierowcy_PoinformujOProblemie {

	private Kierowca kierowca;
	private Po³o¿enie ciê¿arówki po³o¿enie ciê¿arówki;
	private Zdarzenie na trasie zdarzenie na trasie;
	private Zlecenie zlecenie;

	public FormularzKierowcy_PoinformujOProblemie(){

	}

	~FormularzKierowcy_PoinformujOProblemie(){

	}

	/// 
	/// <param name="zdarzenie"></param>
	public Powiadomienie e-mail potwierdŸ(Zdarzenie na trasie zdarzenie){

		return null;
	}

	public Ster_PoinformujOProblemie Ster_PoinformujOProblemie{
		get{
			return m_Ster_PoinformujOProblemie;
		}
		set{
			m_Ster_PoinformujOProblemie = value;
		}
	}

	public void wyœwietlSzablonRejestrowaniaProblemu(){

	}

	public void zg³oœProblemDyspozytorowi(){

	}

}//end FormularzKierowcy_PoinformujOProblemie