///////////////////////////////////////////////////////////
//  FormularzKierowcy_ZarejestrujPrzyjêcieZlecenia.cs
//  Implementation of the Class FormularzKierowcy_ZarejestrujPrzyjêcieZlecenia
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:02:34
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierowcy_ZarejestrujPrzyjêcieZlecenia {

	private Datetime czas;
	private Kierowca kierowca;
	private Zlecenie zlecenie;

	public FormularzKierowcy_ZarejestrujPrzyjêcieZlecenia(){

	}

	~FormularzKierowcy_ZarejestrujPrzyjêcieZlecenia(){

	}

	/// 
	/// <param name="zlecenie"></param>
	public void przyjmijZlecenie(Zlecenie zlecenie){

	}

	public Ster_ZarejestrujPrzyjêcieZlecenia Ster_ZarejestrujPrzyjêcieZlecenia{
		get{
			return m_Ster_ZarejestrujPrzyjêcieZlecenia;
		}
		set{
			m_Ster_ZarejestrujPrzyjêcieZlecenia = value;
		}
	}

	public void wyœwietlEkranLogowania(){

	}

	public void wyœwietlKomunikatONieaktualnymLinku(){

	}

	public void wyœwietlKomunikatOZarejestrowaniuPrzyjêciaZlecenia(){

	}

	public void wyœwietlSzczegó³yZlecenia(){

	}

}//end FormularzKierowcy_ZarejestrujPrzyjêcieZlecenia