///////////////////////////////////////////////////////////
//  FormularzDyspozytora_WyœwietlPrzebiegZlecenia.cs
//  Implementation of the Class FormularzDyspozytora_WyœwietlPrzebiegZlecenia
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:02:25
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzDyspozytora_WyœwietlPrzebiegZlecenia {

	private Zlecenie zlecenie;

	public FormularzDyspozytora_WyœwietlPrzebiegZlecenia(){

	}

	~FormularzDyspozytora_WyœwietlPrzebiegZlecenia(){

	}

	public Ster_WyœwietlPrzebiegZlecenia Ster_WyœwietlPrzebiegZlecenia{
		get{
			return m_Ster_WyœwietlPrzebiegZlecenia;
		}
		set{
			m_Ster_WyœwietlPrzebiegZlecenia = value;
		}
	}

	/// 
	/// <param name="zlecenie"></param>
	public void wyœwietlMenuKontekstowe(Zlecenie zlecenie){

	}

	/// 
	/// <param name="zlecenie"></param>
	public void wyœwietlPrzebiegZlecenia(Zlecenie zlecenie){

	}

	/// 
	/// <param name="zlecenie"></param>
	public void zaznaczZlecenie(Zlecenie zlecenie){

	}

}//end FormularzDyspozytora_WyœwietlPrzebiegZlecenia