///////////////////////////////////////////////////////////
//  Ster_WyœwietlPrzebiegZlecenia.cs
//  Implementation of the Class Ster_WyœwietlPrzebiegZlecenia
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:13:34
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_WyœwietlPrzebiegZlecenia {

	private Zlecenie zlecenie;

	public Ster_WyœwietlPrzebiegZlecenia(){

	}

	~Ster_WyœwietlPrzebiegZlecenia(){

	}

	/// 
	/// <param name="zlecenie"></param>
	public Zlecenie pobierzPrzebiegZlecenia(Zlecenie zlecenie){

		return null;
	}

	public Trasa Trasa{
		get{
			return m_Trasa;
		}
		set{
			m_Trasa = value;
		}
	}

}//end Ster_WyœwietlPrzebiegZlecenia