///////////////////////////////////////////////////////////
//  Ster_ZarejestrujWyjazd.cs
//  Implementation of the Class Ster_ZarejestrujWyjazd
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:13:39
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZarejestrujWyjazd {

	private Datetime czas;
	private Kierowca kierowca;
	private Zlecenie zlecenie;

	public Ster_ZarejestrujWyjazd(){

	}

	~Ster_ZarejestrujWyjazd(){

	}

	public Trasa Trasa{
		get{
			return m_Trasa;
		}
		set{
			m_Trasa = value;
		}
	}

	public void zarejestrujWyjazd(){

	}

}//end Ster_ZarejestrujWyjazd