///////////////////////////////////////////////////////////
//  Ster_PoinformujOProblemie.cs
//  Implementation of the Class Ster_PoinformujOProblemie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:13:27
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_PoinformujOProblemie {

	private Kierowca kierowca;
	private Po³o¿enie ciê¿arówki po³o¿enie ciê¿arówki;
	private Zdarzenie na trasie zdarzenie na trasie;
	private Zlecenie zlecenie;

	public Ster_PoinformujOProblemie(){

	}

	~Ster_PoinformujOProblemie(){

	}

	public Powiadomienie e-mail Powiadomienie e-mail{
		get{
			return m_Powiadomienie e-mail;
		}
		set{
			m_Powiadomienie e-mail = value;
		}
	}

	/// 
	/// <param name="zdarzenie"></param>
	public void utwórzPowiadomienie(Zdarzenie na trasie zdarzenie){

	}

}//end Ster_PoinformujOProblemie