///////////////////////////////////////////////////////////
//  Ster_ZarejestrujPrzyjêcieZlecenia.cs
//  Implementation of the Class Ster_ZarejestrujPrzyjêcieZlecenia
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:13:36
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZarejestrujPrzyjêcieZlecenia {

	private Datetime czas;
	private Kierowca kierowca;
	private Zlecenie zlecenie;

	public Ster_ZarejestrujPrzyjêcieZlecenia(){

	}

	~Ster_ZarejestrujPrzyjêcieZlecenia(){

	}

	public void pobierzSzczegó³yZlecenia(){

	}

	public void zaloguj(){

	}

	/// 
	/// <param name="zlecenie"></param>
	/// <param name="kierowca"></param>
	public void zarejestrujPrzyjêcieZlecenia(Zlecenie zlecenie, Kierowca kierowca){

	}

	public Zlecenie Zlecenie{
		get{
			return zlecenie;
		}
		set{
			zlecenie = value;
		}
	}

}//end Ster_ZarejestrujPrzyjêcieZlecenia