///////////////////////////////////////////////////////////
//  Ster_ZarejestrujZakoñczenieRealizacjiZlecenia.cs
//  Implementation of the Class Ster_ZarejestrujZakoñczenieRealizacjiZlecenia
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:13:42
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZarejestrujZakoñczenieRealizacjiZlecenia {

	private Datetime czas;
	private Kierowca kierowca;
	private Zlecenie zlecenie;

	public Ster_ZarejestrujZakoñczenieRealizacjiZlecenia(){

	}

	~Ster_ZarejestrujZakoñczenieRealizacjiZlecenia(){

	}

	public Trasa Trasa{
		get{
			return m_Trasa;
		}
		set{
			m_Trasa = value;
		}
	}

	public void zarejestrujKoniecZlecenia(){

	}

}//end Ster_ZarejestrujZakoñczenieRealizacjiZlecenia