///////////////////////////////////////////////////////////
//  Ster_WyœlijInformacjêOPo³o¿eniuCiê¿arówki.cs
//  Implementation of the Class Ster_WyœlijInformacjêOPo³o¿eniuCiê¿arówki
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:13:31
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_WyœlijInformacjêOPo³o¿eniuCiê¿arówki {

	private Po³o¿enie ciê¿arówki po³o¿enie ciê¿arówki;

	public Ster_WyœlijInformacjêOPo³o¿eniuCiê¿arówki(){

	}

	~Ster_WyœlijInformacjêOPo³o¿eniuCiê¿arówki(){

	}

	public void zarejestruj po³o¿enie ciê¿arówki(){

	}

}//end Ster_WyœlijInformacjêOPo³o¿eniuCiê¿arówki