///////////////////////////////////////////////////////////
//  Ster_ZarejestrujZdarzenieNaTrasie.cs
//  Implementation of the Class Ster_ZarejestrujZdarzenieNaTrasie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:13:46
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZarejestrujZdarzenieNaTrasie {

	private Kierowca kierowca;
	private Po³o¿enie ciê¿arówki po³o¿enie ciê¿arówki;
	private Zdarzenie na trasie zdarzenie na trasie;
	private Zlecenie zlecenie;

	public Ster_ZarejestrujZdarzenieNaTrasie(){

	}

	~Ster_ZarejestrujZdarzenieNaTrasie(){

	}

	public Trasa Trasa{
		get{
			return m_Trasa;
		}
		set{
			m_Trasa = value;
		}
	}

	/// 
	/// <param name="zdarzenie"></param>
	/// <param name="trasa"></param>
	public void utwórzZdarzenie(Zdarzenie na trasie zdarzenie, Trasa trasa){

	}

	/// 
	/// <param name="trasa"></param>
	public void wyœlijPowiadomienieDoDyspozytora(Trasa trasa){

	}

}//end Ster_ZarejestrujZdarzenieNaTrasie