///////////////////////////////////////////////////////////
//  FormularzKierownika_EdytujDanePojazdu.cs
//  Implementation of the Class FormularzKierownika_EdytujDanePojazdu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:06:48
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_EdytujDanePojazdu {

	private Pojazd pojazd;

	public FormularzKierownika_EdytujDanePojazdu(){

	}

	~FormularzKierownika_EdytujDanePojazdu(){

	}

	public Ster_EdytujDanePojazdu Ster_EdytujDanePojazdu{
		get{
			return m_Ster_EdytujDanePojazdu;
		}
		set{
			m_Ster_EdytujDanePojazdu = value;
		}
	}

	/// 
	/// <param name="b³êdy"></param>
	public void wyœwietlB³êdy(List<string> b³êdy){

	}

	public void wyœwietlFormularzEdycjiDanychPojazdu(){

	}

	public void zapisz(){

	}

}//end FormularzKierownika_EdytujDanePojazdu