///////////////////////////////////////////////////////////
//  FormularzKierownika_ZmodyfikujPrzypisanieKierowcyDoPojazdu.cs
//  Implementation of the Class FormularzKierownika_ZmodyfikujPrzypisanieKierowcyDoPojazdu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:07:09
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_ZmodyfikujPrzypisanieKierowcyDoPojazdu {

	private Kierowca kierowca;
	private Pojazd pojazd;

	public FormularzKierownika_ZmodyfikujPrzypisanieKierowcyDoPojazdu(){

	}

	~FormularzKierownika_ZmodyfikujPrzypisanieKierowcyDoPojazdu(){

	}

	/// 
	/// <param name="kryteria"></param>
	public void filtrujListêKierowców(List<string> kryteria){

	}

	/// 
	/// <param name="pojazd"></param>
	/// <param name="kierowca"></param>
	public void przypisz)PojazdDoKierowcy(Pojazd pojazd, Kierowca kierowca){

	}

	public Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu{
		get{
			return m_Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu;
		}
		set{
			m_Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu = value;
		}
	}

	/// 
	/// <param name="pojazd"></param>
	/// <param name="kierowca"></param>
	public void usuñPrzypisaniePojazduDoKierowcy(Pojazd pojazd, Kierowca kierowca){

	}

	/// 
	/// <param name="pojazd"></param>
	public void wyœwietlFormularzPrzypisaniaKierowcyDoPojazdu(Pojazd pojazd){

	}

	/// 
	/// <param name="kierowca"></param>
	public void wyœwietlMenuKontekstowe(Kierowca kierowca){

	}

	/// 
	/// <param name="kierowca"></param>
	public void zaznaczKierowcê(Kierowca kierowca){

	}

}//end FormularzKierownika_ZmodyfikujPrzypisanieKierowcyDoPojazdu