///////////////////////////////////////////////////////////
//  FormularzKierownika_DodajNowyPojazd.cs
//  Implementation of the Class FormularzKierownika_DodajNowyPojazd
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:06:44
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_DodajNowyPojazd {

	private Pojazd pojazd;

	public FormularzKierownika_DodajNowyPojazd(){

	}

	~FormularzKierownika_DodajNowyPojazd(){

	}

	public void dodajPojazd(){

	}

	public Ster_DodajNowyPojazd Ster_DodajNowyPojazd{
		get{
			return m_Ster_DodajNowyPojazd;
		}
		set{
			m_Ster_DodajNowyPojazd = value;
		}
	}

}//end FormularzKierownika_DodajNowyPojazd