///////////////////////////////////////////////////////////
//  FormularzKierownika_ZaktualizujDaneIstniej¹cegoPojazdu.cs
//  Implementation of the Class FormularzKierownika_ZaktualizujDaneIstniej¹cegoPojazdu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:06:59
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_ZaktualizujDaneIstniej¹cegoPojazdu {

	private Pojazd pojazd;

	public FormularzKierownika_ZaktualizujDaneIstniej¹cegoPojazdu(){

	}

	~FormularzKierownika_ZaktualizujDaneIstniej¹cegoPojazdu(){

	}

	/// 
	/// <param name="pojazd"></param>
	public void edytuj(Pojazd pojazd){

	}

	public Ster_ZaktualizujDaneIstniej¹cegoPojazdu Ster_ZaktualizujDaneIstniej¹cegoPojazdu{
		get{
			return m_Ster_ZaktualizujDaneIstniej¹cegoPojazdu;
		}
		set{
			m_Ster_ZaktualizujDaneIstniej¹cegoPojazdu = value;
		}
	}

	public void wyœwietlFormularzAktualizacjiDanychPojazdu(){

	}

	/// 
	/// <param name="pojazdy"></param>
	public void wyœwietlListêPojazdów(Lista pojazdów pojazdy){

	}

	/// 
	/// <param name="pojazd"></param>
	public void wyœwietlMenuKontekstowe(Pojazd pojazd){

	}

	/// 
	/// <param name="pojazd"></param>
	public void zaznaczPojazd(Pojazd pojazd){

	}

}//end FormularzKierownika_ZaktualizujDaneIstniej¹cegoPojazdu