///////////////////////////////////////////////////////////
//  FormularzKierownika_UsuñIstniej¹cyPojazd.cs
//  Implementation of the Class FormularzKierownika_UsuñIstniej¹cyPojazd
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:06:56
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FormularzKierownika_UsuñIstniej¹cyPojazd {

	private Pojazd pojazd;

	public FormularzKierownika_UsuñIstniej¹cyPojazd(){

	}

	~FormularzKierownika_UsuñIstniej¹cyPojazd(){

	}

	public Ster_UsuñIstniej¹cyPojazd Ster_UsuñIstniej¹cyPojazd{
		get{
			return m_Ster_UsuñIstniej¹cyPojazd;
		}
		set{
			m_Ster_UsuñIstniej¹cyPojazd = value;
		}
	}

	/// 
	/// <param name="pojazd"></param>
	public void usuñPojazd(Pojazd pojazd){

	}

	/// 
	/// <param name="pojazd"></param>
	public void wyœwietlMenuKontekstowe(Pojazd pojazd){

	}

	/// 
	/// <param name="pojazd"></param>
	public void zaznaczPojazd(Pojazd pojazd){

	}

}//end FormularzKierownika_UsuñIstniej¹cyPojazd