///////////////////////////////////////////////////////////
//  Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu.cs
//  Implementation of the Class Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:16:40
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu {

	private Kierowca kierowca;
	private Pojazd pojazd;

	public Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu(){

	}

	~Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu(){

	}

	public Lista kierowców Lista kierowców{
		get{
			return m_Lista kierowców;
		}
		set{
			m_Lista kierowców = value;
		}
	}

	public Lista kierowców pobierzListêKierowców(){

		return null;
	}

	public Pojazd Pojazd{
		get{
			return pojazd;
		}
		set{
			pojazd = value;
		}
	}

	/// 
	/// <param name="pojazd"></param>
	/// <param name="kierowca"></param>
	public void przypiszPojazdDoKierowcy(Kierowca pojazd, Pojazd kierowca){

	}

	/// 
	/// <param name="pojazd"></param>
	/// <param name="kierowca"></param>
	public void usuñPrzypisaniePojazduDoKierowcy(Pojazd pojazd, Kierowca kierowca){

	}

}//end Ster_ZmodyfikujPrzypisanieKierowcyDoPojazdu