///////////////////////////////////////////////////////////
//  Ster_DodajNowyPojazd.cs
//  Implementation of the Class Ster_DodajNowyPojazd
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:16:27
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_DodajNowyPojazd {

	private Pojazd pojazd;

	public Ster_DodajNowyPojazd(){

	}

	~Ster_DodajNowyPojazd(){

	}

	public Lista pojazdów Lista pojazdów{
		get{
			return m_Lista pojazdów;
		}
		set{
			m_Lista pojazdów = value;
		}
	}

	public Pojazd Pojazd{
		get{
			return pojazd;
		}
		set{
			pojazd = value;
		}
	}

	public Pojazd utwórzPojazd(){

		return null;
	}

}//end Ster_DodajNowyPojazd