///////////////////////////////////////////////////////////
//  Ster_UsuñIstniej¹cyPojazd.cs
//  Implementation of the Class Ster_UsuñIstniej¹cyPojazd
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:16:33
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_UsuñIstniej¹cyPojazd {

	private Pojazd pojazd;

	public Ster_UsuñIstniej¹cyPojazd(){

	}

	~Ster_UsuñIstniej¹cyPojazd(){

	}

	public Lista pojazdów Lista pojazdów{
		get{
			return m_Lista pojazdów;
		}
		set{
			m_Lista pojazdów = value;
		}
	}

	public Pojazd Pojazd{
		get{
			return pojazd;
		}
		set{
			pojazd = value;
		}
	}

	/// 
	/// <param name="pojazd"></param>
	public void usuñPojazd(Pojazd pojazd){

	}

}//end Ster_UsuñIstniej¹cyPojazd