///////////////////////////////////////////////////////////
//  Ster_ZaktualizujDaneIstniej¹cegoPojazdu.cs
//  Implementation of the Class Ster_ZaktualizujDaneIstniej¹cegoPojazdu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:16:36
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_ZaktualizujDaneIstniej¹cegoPojazdu {

	private Pojazd pojazd;

	public Ster_ZaktualizujDaneIstniej¹cegoPojazdu(){

	}

	~Ster_ZaktualizujDaneIstniej¹cegoPojazdu(){

	}

	public Lista pojazdów Lista pojazdów{
		get{
			return m_Lista pojazdów;
		}
		set{
			m_Lista pojazdów = value;
		}
	}

	public Lista pojazdów pobierzListêPojazdów(){

		return null;
	}

}//end Ster_ZaktualizujDaneIstniej¹cegoPojazdu