///////////////////////////////////////////////////////////
//  Ster_EdytujDanePojazdu.cs
//  Implementation of the Class Ster_EdytujDanePojazdu
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2024 20:16:30
//  Original author: Damian Wójcik
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Ster_EdytujDanePojazdu {

	private Pojazd pojazd;

	public Ster_EdytujDanePojazdu(){

	}

	~Ster_EdytujDanePojazdu(){

	}

	public Pojazd Pojazd{
		get{
			return pojazd;
		}
		set{
			pojazd = value;
		}
	}

	/// 
	/// <param name="pojazd"></param>
	public void waliduj(Pojazd pojazd){

	}

	/// 
	/// <param name="pojazd"></param>
	public void zapisz(Pojazd pojazd){

	}

}//end Ster_EdytujDanePojazdu